SilentEye: SEFormatJPEG::PixelGroup Class Reference
SEFormatJPEG::PixelGroup Class Reference
The pixel group wich represent a block. (8x8 in the Jpeg format)
#include <groupedimage.h>
Public Member Functions
PixelGroup (QObject *parent=0)
~PixelGroup ()
QPointer< YCbCr > pixel (quint8, quint8)
Get pixel at specified position.
void setPixel (quint8, quint8, QPointer< YCbCr >)
Change pixel at specified position.
float miv () const
void updateMivTo (float)
Mean intensity value of the Y component pixels.
QString toString () const
PixelGroup (QObject *parent=0)
~PixelGroup ()
QPointer< YCbCr > pixel (quint8, quint8)
void setPixel (quint8, quint8, QPointer< YCbCr >)
float miv () const
void updateMivTo (float)
QString toString () const
Static Public Member Functions
static quint8 width ()
static quint8 height ()
static quint8 width ()
static quint8 height ()
Private Member Functions
void computeMIV ()
Compute the Mean Intensity Value (the average of the Y component of the YCbCr format) of the block and store it in the MIV attribute.
void updatePixelMiv (QPointer< YCbCr >, double)
Alter pixels of the block making the Mean Intensity Value to the destMIV.
void computeMIV ()
void updatePixelMiv (QPointer< YCbCr >, double)
Private Attributes
QPointer< Logger > m_logger
Logger.
QVector< QPointer< YCbCr > > m_pixels
Pixels contained in the pixel group.
float m_miv
Mean intensity value of the Y component pixels.
Detailed Description
The pixel group wich represent a block. (8x8 in the Jpeg format)
Each pixel in the pixel group is encode using the YCbCr format. In this class, pixel groups aren't considered as two dimention arrays. Blocs are managed in a one dimention array
Definition at line 37 of file groupedimage.h.
Constructor & Destructor Documentation
SEFormatJPEG::PixelGroup::PixelGroup (QObject * parent = 0)
Definition at line 27 of file groupedimage.cpp.
References m_logger, m_miv, m_pixels, PIXEL_GROUP_SIZE, and SEFormatJPEG::setObjectName().
SEFormatJPEG::PixelGroup::~PixelGroup ()
Definition at line 36 of file groupedimage.cpp.
References m_logger.
SEFormatJPEG::PixelGroup::PixelGroup (QObject * parent = 0)
SEFormatJPEG::PixelGroup::~PixelGroup ()
Member Function Documentation
void SEFormatJPEG::PixelGroup::computeMIV () [private]
Compute the Mean Intensity Value (the average of the Y component of the YCbCr format) of the block and store it in the MIV attribute.
Definition at line 149 of file groupedimage.cpp.
References m_miv, m_pixels, and PIXEL_GROUP_SIZE.
Referenced by setPixel(), and updateMivTo().
void SEFormatJPEG::PixelGroup::computeMIV () [private]
static quint8 SEFormatJPEG::PixelGroup::height () [inline, static]
Definition at line 71 of file groupedimage.h.
References PIXEL_GROUP_SIZE.
Referenced by SEFormatJPEG::GroupedImage::GroupedImage(), and updateMivTo().
static quint8 SEFormatJPEG::PixelGroup::height () [inline, static]
Definition at line 53 of file groupedimage.h.
References PIXEL_GROUP_SIZE.
float SEFormatJPEG::PixelGroup::miv () const
Definition at line 83 of file groupedimage.cpp.
References m_miv.
float SEFormatJPEG::PixelGroup::miv () const
QPointer<YCbCr> SEFormatJPEG::PixelGroup::pixel (quint8 , quint8)
QPointer< YCbCr > SEFormatJPEG::PixelGroup::pixel (quint8 x, quint8 y)
Get pixel at specified position.
Parameters:
x horizontal position
y vertical position
Definition at line 51 of file groupedimage.cpp.
References m_logger, m_pixels, and PIXEL_GROUP_SIZE.
Referenced by setPixel(), and updateMivTo().
void SEFormatJPEG::PixelGroup::setPixel (quint8 x, quint8 y, QPointer< YCbCr > pixel)
Change pixel at specified position.
Parameters:
x horizontal position
y vertical position
Definition at line 67 of file groupedimage.cpp.
References computeMIV(), m_logger, m_pixels, pixel(), and PIXEL_GROUP_SIZE.
void SEFormatJPEG::PixelGroup::setPixel (quint8 , quint8 , QPointer< YCbCr >)
QString SEFormatJPEG::PixelGroup::toString () const
Definition at line 175 of file groupedimage.cpp.
References m_miv, m_pixels, and PIXEL_GROUP_SIZE.
QString SEFormatJPEG::PixelGroup::toString () const
void SEFormatJPEG::PixelGroup::updateMivTo (float destMiv)
Mean intensity value of the Y component pixels.
Definition at line 88 of file groupedimage.cpp.
References computeMIV(), height(), m_logger, m_miv, pixel(), updatePixelMiv(), and width().
void SEFormatJPEG::PixelGroup::updateMivTo (float)
void SEFormatJPEG::PixelGroup::updatePixelMiv (QPointer< YCbCr > , double) [private]
void SEFormatJPEG::PixelGroup::updatePixelMiv (QPointer< YCbCr > p, double distance) [private]
Alter pixels of the block making the Mean Intensity Value to the destMIV.
Definition at line 129 of file groupedimage.cpp.
Referenced by updateMivTo().
static quint8 SEFormatJPEG::PixelGroup::width () [inline, static]
Definition at line 52 of file groupedimage.h.
References PIXEL_GROUP_SIZE.
static quint8 SEFormatJPEG::PixelGroup::width () [inline, static]
Definition at line 70 of file groupedimage.h.
References PIXEL_GROUP_SIZE.
Referenced by SEFormatJPEG::GroupedImage::compacteAndGroupImage(), SEFormatJPEG::GroupedImage::GroupedImage(), SEFormatJPEG::GroupedImage::toImage(), and updateMivTo().
Member Data Documentation
QPointer< Logger > SEFormatJPEG::PixelGroup::m_logger [private]
Logger.
Definition at line 40 of file groupedimage.h.
Referenced by pixel(), PixelGroup(), setPixel(), updateMivTo(), and ~PixelGroup().
float SEFormatJPEG::PixelGroup::m_miv [private]
Mean intensity value of the Y component pixels.
Definition at line 45 of file groupedimage.h.
Referenced by computeMIV(), miv(), PixelGroup(), toString(), and updateMivTo().
QVector< QPointer< YCbCr > > SEFormatJPEG::PixelGroup::m_pixels [private]
Pixels contained in the pixel group.
Definition at line 43 of file groupedimage.h.
Referenced by computeMIV(), pixel(), PixelGroup(), setPixel(), and toString().
The documentation for this class was generated from the following files:
modules/seformatjpeg/groupedimage.h
modules/seformatjpegold/seformatjpeg/groupedimage.h
modules/seformatjpeg/groupedimage.cpp
modules/seformatjpegold/seformatjpeg/groupedimage.cpp