SilentEye: SEFormatBMP::OptionWidget Class Reference
SEFormatBMP::OptionWidget Class Reference
#include <optionwidget.h>
Signals
void optionHasChanged ()
Public Member Functions
OptionWidget (QWidget *parent=0)
~OptionWidget ()
int nbBits () const
bool isRedUsed () const
bool isGreenUsed () const
bool isBlueUsed () const
ImageBMP::DataDistribution distribution () const
ImageBMP::HeaderPosition headerPosition () const
Protected Slots
void advButtonPressed (bool)
void qualityChanged (int=-1)
void settingsChanged (int=-1)
Private Attributes
QPointer< Logger > m_logger
bool m_dontUpdate
Detailed Description
Definition at line 28 of file optionwidget.h.
Constructor & Destructor Documentation
SEFormatBMP::OptionWidget::OptionWidget (QWidget * parent = 0)
SEFormatBMP::OptionWidget::~OptionWidget ()
Definition at line 42 of file optionwidget.cpp.
References m_logger.
Member Function Documentation
void SEFormatBMP::OptionWidget::advButtonPressed (bool value) [protected, slot]
Definition at line 106 of file optionwidget.cpp.
ImageBMP::DataDistribution SEFormatBMP::OptionWidget::distribution () const
Definition at line 67 of file optionwidget.cpp.
References SEFormatBMP::ImageBMP::EQUI, SEFormatBMP::ImageBMP::INLINE, and m_logger.
Referenced by SEFormatBMP::SEFormatBmp::updateImage().
ImageBMP::HeaderPosition SEFormatBMP::OptionWidget::headerPosition () const
Definition at line 85 of file optionwidget.cpp.
References SEFormatBMP::ImageBMP::BOTTOM, m_logger, SEFormatBMP::ImageBMP::SIGNATURE, and SEFormatBMP::ImageBMP::TOP.
Referenced by SEFormatBMP::SEFormatBmp::updateImage().
bool SEFormatBMP::OptionWidget::isBlueUsed () const
Definition at line 62 of file optionwidget.cpp.
Referenced by settingsChanged(), and SEFormatBMP::SEFormatBmp::updateImage().
bool SEFormatBMP::OptionWidget::isGreenUsed () const
Definition at line 57 of file optionwidget.cpp.
Referenced by settingsChanged(), and SEFormatBMP::SEFormatBmp::updateImage().
bool SEFormatBMP::OptionWidget::isRedUsed () const
Definition at line 52 of file optionwidget.cpp.
Referenced by settingsChanged(), and SEFormatBMP::SEFormatBmp::updateImage().
int SEFormatBMP::OptionWidget::nbBits () const
Definition at line 47 of file optionwidget.cpp.
Referenced by settingsChanged(), and SEFormatBMP::SEFormatBmp::updateImage().
void SEFormatBMP::OptionWidget::optionHasChanged () [signal]
Referenced by settingsChanged().
void SEFormatBMP::OptionWidget::qualityChanged (int value = -1) [protected, slot]
Definition at line 111 of file optionwidget.cpp.
References m_dontUpdate, m_logger, and settingsChanged().
void SEFormatBMP::OptionWidget::settingsChanged (int value = -1) [protected, slot]
Definition at line 162 of file optionwidget.cpp.
References isBlueUsed(), isGreenUsed(), isRedUsed(), m_dontUpdate, m_logger, nbBits(), and optionHasChanged().
Referenced by qualityChanged().
Member Data Documentation
bool SEFormatBMP::OptionWidget::m_dontUpdate [private]
Definition at line 34 of file optionwidget.h.
Referenced by qualityChanged(), and settingsChanged().
QPointer<Logger> SEFormatBMP::OptionWidget::m_logger [private]
Definition at line 30 of file optionwidget.h.
Referenced by distribution(), SEFormatJPEG::OptionWidget::headerPosition(), headerPosition(), qualityChanged(), settingsChanged(), and ~OptionWidget().
The documentation for this class was generated from the following files:
modules/seformatbmp/optionwidget.h
modules/seformatbmp/optionwidget.cpp