SilentEye: SilentEyeFramework::Image Class Reference
SilentEyeFramework::Image Class Reference
Generic representation of image which can load and hide specific data according to it's format.
#include <image.h>
Public Member Functions
Image ()
~Image ()
Image (const QString &filepath)
Image (const QPixmap &pixmap, QString filePath="Pixmap")
Image (const Image &img)
Image (Image *img)
int imgWidth () const
int imgHeight () const
int quality () const
Protected Attributes
int m_width
Image width.
int m_height
Image height.
int m_quality
Quality (in pourcent)
Detailed Description
Generic representation of image which can load and hide specific data according to it's format.
Definition at line 30 of file image.h.
Constructor & Destructor Documentation
SilentEyeFramework::Image::Image ()
SilentEyeFramework::Image::~Image ()
Definition at line 64 of file image.cpp.
SilentEyeFramework::Image::Image (const QString & filepath)
Definition at line 28 of file image.cpp.
References SilentEyeFramework::m_type, and SEFormatBMP::setObjectName().
SilentEyeFramework::Image::Image (const QPixmap & pixmap, QString filePath = "Pixmap")
Definition at line 37 of file image.cpp.
References SilentEyeFramework::m_type, and SEFormatBMP::setObjectName().
SilentEyeFramework::Image::Image (const Image & img)
Definition at line 46 of file image.cpp.
References imgHeight(), imgWidth(), SilentEyeFramework::m_type, and SEFormatBMP::setObjectName().
SilentEyeFramework::Image::Image (Image * img)
Definition at line 55 of file image.cpp.
References imgHeight(), imgWidth(), SilentEyeFramework::m_type, and SEFormatBMP::setObjectName().
Member Function Documentation
int SilentEyeFramework::Image::imgHeight () const
Definition at line 74 of file image.cpp.
References m_height.
Referenced by SEFormatBMP::ImageBMP::capacity(), SEFormatBMP::ImageBMP::computeDistributionStep(), SEFormatBMP::ImageBMP::computeHeaderPosition(), and Image().
int SilentEyeFramework::Image::imgWidth () const
Definition at line 69 of file image.cpp.
References m_width.
Referenced by SEFormatBMP::ImageBMP::capacity(), SEFormatBMP::ImageBMP::computeDistributionStep(), SEFormatBMP::ImageBMP::computeHeaderPosition(), SEFormatBMP::ImageBMP::computeNewPosition(), and Image().
int SilentEyeFramework::Image::quality () const
Definition at line 79 of file image.cpp.
References m_quality.
Referenced by SilentEye::PropertyDialog::setMedia().
Member Data Documentation
int SilentEyeFramework::Image::m_height [protected]
Image height.
Definition at line 36 of file image.h.
Referenced by imgHeight().
int SilentEyeFramework::Image::m_quality [protected]
Quality (in pourcent)
Reimplemented in SEFormatJPEG::ImageJPEG.
Definition at line 38 of file image.h.
Referenced by quality().
int SilentEyeFramework::Image::m_width [protected]
Image width.
Definition at line 34 of file image.h.
Referenced by imgWidth().
The documentation for this class was generated from the following files:
sef/image.h
sef/image.cpp