SilentEye: SilentEyeFramework::Config Class Reference
SilentEyeFramework::Config Class Reference
Manage configuration for application (read/write in xml file)
#include <config.h>
Public Member Functions
Config (QObject *parent=0)
Config (QString filePath, QString filename, bool=false, QObject *parent=0)
Config (const QString &content, QObject *parent=0)
Config (const Config &config)
~Config ()
QString filename () const
QString filepath () const
QMap< QString, QString > values () const
void set (const QString name, const QString value)
QString get (const QString name) const
bool contains (const QString name) const
void save ()
bool isLoaded () const
Config & operator= (const Config &config)
Private Member Functions
bool load ()
Private Attributes
bool m_isLoaded
QString m_filename
QString m_filepath
QString m_content
QMap< QString, QString > m_valueMap
QPointer< Logger > m_logger
Detailed Description
Manage configuration for application (read/write in xml file)
Definition at line 28 of file config.h.
Constructor & Destructor Documentation
SilentEyeFramework::Config::Config (QObject * parent = 0)
SilentEyeFramework::Config::Config (QString filePath, QString filename, bool hasExt = false, QObject * parent = 0)
Definition at line 31 of file config.cpp.
References filename(), load(), m_filename, m_filepath, m_isLoaded, m_logger, and SEFormatBMP::setObjectName().
SilentEyeFramework::Config::Config (const QString & content, QObject * parent = 0)
Definition at line 48 of file config.cpp.
References SilentEyeFramework::m_filename, SilentEyeFramework::m_filepath, SilentEyeFramework::m_isLoaded, SilentEyeFramework::m_logger, and SEFormatBMP::setObjectName().
SilentEyeFramework::Config::Config (const Config & config)
Definition at line 60 of file config.cpp.
References filename(), m_filename, m_logger, m_valueMap, SEFormatBMP::setObjectName(), and values().
SilentEyeFramework::Config::~Config ()
Definition at line 68 of file config.cpp.
References m_logger.
Member Function Documentation
bool SilentEyeFramework::Config::contains (const QString name) const
Definition at line 95 of file config.cpp.
References m_valueMap.
QString SilentEyeFramework::Config::filename () const
Definition at line 75 of file config.cpp.
References m_filename.
Referenced by Config(), and operator=().
QString SilentEyeFramework::Config::filepath () const
Definition at line 80 of file config.cpp.
References m_filepath.
Referenced by operator=().
QString SilentEyeFramework::Config::get (const QString name) const
Definition at line 105 of file config.cpp.
References m_valueMap.
Referenced by SilentEye::UpdateDialog::httpFinished(), SilentEye::UpdateDialog::UpdateDialog(), and SilentEye::Controller::updateProxySettings().
bool SilentEyeFramework::Config::isLoaded () const
Definition at line 90 of file config.cpp.
References m_isLoaded.
Referenced by SilentEye::UpdateDialog::UpdateDialog().
bool SilentEyeFramework::Config::load () [private]
Definition at line 143 of file config.cpp.
References m_content, m_filename, m_filepath, m_logger, and m_valueMap.
Referenced by Config().
Config & SilentEyeFramework::Config::operator= (const Config & config)
Definition at line 192 of file config.cpp.
References filename(), filepath(), m_filename, m_filepath, m_valueMap, and values().
void SilentEyeFramework::Config::save ()
Definition at line 113 of file config.cpp.
References m_filename, m_filepath, m_logger, and m_valueMap.
void SilentEyeFramework::Config::set (const QString name, const QString value)
Definition at line 100 of file config.cpp.
References m_valueMap.
QMap< QString, QString > SilentEyeFramework::Config::values () const
Definition at line 85 of file config.cpp.
References m_valueMap.
Referenced by Config(), and operator=().
Member Data Documentation
QString SilentEyeFramework::Config::m_content [private]
Definition at line 34 of file config.h.
Referenced by load().
QString SilentEyeFramework::Config::m_filename [private]
Definition at line 32 of file config.h.
Referenced by Config(), filename(), load(), operator=(), and save().
QString SilentEyeFramework::Config::m_filepath [private]
Definition at line 33 of file config.h.
Referenced by Config(), filepath(), load(), operator=(), and save().
bool SilentEyeFramework::Config::m_isLoaded [private]
Definition at line 31 of file config.h.
Referenced by Config(), and isLoaded().
QPointer<Logger> SilentEyeFramework::Config::m_logger [private]
Definition at line 36 of file config.h.
Referenced by Config(), load(), save(), and ~Config().
QMap<QString, QString> SilentEyeFramework::Config::m_valueMap [private]
Definition at line 35 of file config.h.
Referenced by Config(), contains(), get(), load(), operator=(), save(), set(), and values().
The documentation for this class was generated from the following files:
sef/config.h
sef/config.cpp