SilentEye: SECryptoAES256::SECryptoAES256 Class Reference
SECryptoAES256::SECryptoAES256 Class Reference
#include <secryptoaes256.h>
Public Member Functions
SECryptoAES256 ()
~SECryptoAES256 ()
QString name () const
Plug-in name (ex: FooBar)
QString version () const
Plug-in version (ex: 1.2.0)
QString status ()
Current status of the module (ex: KO|qca2-plugin-ossl missing)
QString typeSupported () const
Type supported (ex: BMP, JPEG, AES128, etc.)
QPointer< EncodedData > encode (QString key, QPointer< EncodedData > msg)
Encrypte data using a specific key.
QPointer< EncodedData > decode (QString key, QPointer< EncodedData > data)
Decrypte data using a specific key.
Private Member Functions
Q_INTERFACES (SilentEyeFramework::CryptoModuleInterface)
void init ()
QCA::SecureArray initializationVector (QString)
Private Attributes
QPointer< Logger > m_logger
bool m_isQcaCompatible
QCA::SymmetricKey m_key
QCA::Initializer * m_init
Detailed Description
Definition at line 33 of file secryptoaes256.h.
Constructor & Destructor Documentation
SECryptoAES256::SECryptoAES256::SECryptoAES256 ()
SECryptoAES256::SECryptoAES256::~SECryptoAES256 ()
Definition at line 30 of file secryptoaes256.cpp.
References m_init, and m_logger.
Member Function Documentation
QPointer< EncodedData > SECryptoAES256::SECryptoAES256::decode (QString key, QPointer< EncodedData > data) [virtual]
Decrypte data using a specific key.
Implements SilentEyeFramework::CryptoModuleInterface.
Definition at line 141 of file secryptoaes256.cpp.
References init(), initializationVector(), m_isQcaCompatible, m_key, and m_logger.
QPointer< EncodedData > SECryptoAES256::SECryptoAES256::encode (QString key, QPointer< EncodedData > msg) [virtual]
Encrypte data using a specific key.
Implements SilentEyeFramework::CryptoModuleInterface.
Definition at line 100 of file secryptoaes256.cpp.
References init(), initializationVector(), m_isQcaCompatible, m_key, and m_logger.
void SECryptoAES256::SECryptoAES256::init () [private]
Definition at line 37 of file secryptoaes256.cpp.
References m_init, m_isQcaCompatible, m_key, m_logger, and name().
Referenced by decode(), encode(), and status().
QCA::SecureArray SECryptoAES256::SECryptoAES256::initializationVector (QString key) [private]
Definition at line 87 of file secryptoaes256.cpp.
References m_logger.
Referenced by decode(), and encode().
QString SECryptoAES256::SECryptoAES256::name () const [virtual]
Plug-in name (ex: FooBar)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 63 of file secryptoaes256.cpp.
References typeSupported().
Referenced by init().
SECryptoAES256::SECryptoAES256::Q_INTERFACES (SilentEyeFramework::CryptoModuleInterface) [private]
QString SECryptoAES256::SECryptoAES256::status () [virtual]
Current status of the module (ex: KO|qca2-plugin-ossl missing)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 73 of file secryptoaes256.cpp.
References init(), and m_isQcaCompatible.
QString SECryptoAES256::SECryptoAES256::typeSupported () const [virtual]
Type supported (ex: BMP, JPEG, AES128, etc.)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 82 of file secryptoaes256.cpp.
Referenced by name().
QString SECryptoAES256::SECryptoAES256::version () const [virtual]
Plug-in version (ex: 1.2.0)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 68 of file secryptoaes256.cpp.
Member Data Documentation
QCA::Initializer* SECryptoAES256::SECryptoAES256::m_init [private]
Definition at line 42 of file secryptoaes256.h.
Referenced by init(), and ~SECryptoAES256().
bool SECryptoAES256::SECryptoAES256::m_isQcaCompatible [private]
Definition at line 40 of file secryptoaes256.h.
Referenced by decode(), encode(), init(), and status().
QCA::SymmetricKey SECryptoAES256::SECryptoAES256::m_key [private]
Definition at line 41 of file secryptoaes256.h.
Referenced by decode(), encode(), and init().
QPointer<Logger> SECryptoAES256::SECryptoAES256::m_logger [private]
Definition at line 39 of file secryptoaes256.h.
Referenced by decode(), encode(), init(), initializationVector(), and ~SECryptoAES256().
The documentation for this class was generated from the following files:
modules/secryptoaes256/secryptoaes256.h
modules/secryptoaes256/secryptoaes256.cpp