SilentEye: SEFormatWAV::OptionWidget Class Reference
SEFormatWAV::OptionWidget Class Reference
#include <optionwidget.h>
Signals
void optionHasChanged ()
Public Member Functions
OptionWidget (QWidget *parent=0)
~OptionWidget ()
int nbBits () const
int channels () const
AudioWav::DataDistribution distribution () const
AudioWav::HeaderPosition headerPosition () const
Protected Slots
void advButtonPressed (bool)
void qualityChanged (int=-1)
void settingsChanged (int=-1)
Private Attributes
QPointer< Logger > m_logger
bool m_dontUpdate
Detailed Description
Definition at line 28 of file optionwidget.h.
Constructor & Destructor Documentation
SEFormatWAV::OptionWidget::OptionWidget (QWidget * parent = 0)
SEFormatWAV::OptionWidget::~OptionWidget ()
Definition at line 40 of file optionwidget.cpp.
References SEFormatJPEG::OptionWidget::m_logger.
Member Function Documentation
void SEFormatWAV::OptionWidget::advButtonPressed (bool value) [protected, slot]
Definition at line 91 of file optionwidget.cpp.
int SEFormatWAV::OptionWidget::channels () const
Definition at line 50 of file optionwidget.cpp.
Referenced by SEFormatWAV::SEFormatWav::updateAudio().
AudioWav::DataDistribution SEFormatWAV::OptionWidget::distribution () const
Definition at line 55 of file optionwidget.cpp.
References SEFormatJPEG::OptionWidget::m_logger.
Referenced by SEFormatWAV::SEFormatWav::updateAudio().
AudioWav::HeaderPosition SEFormatWAV::OptionWidget::headerPosition () const
Definition at line 73 of file optionwidget.cpp.
References SEFormatJPEG::OptionWidget::m_logger.
Referenced by SEFormatWAV::SEFormatWav::updateAudio().
int SEFormatWAV::OptionWidget::nbBits () const
Definition at line 45 of file optionwidget.cpp.
Referenced by SEFormatWAV::SEFormatWav::updateAudio().
void SEFormatWAV::OptionWidget::optionHasChanged () [signal]
void SEFormatWAV::OptionWidget::qualityChanged (int value = -1) [protected, slot]
Definition at line 96 of file optionwidget.cpp.
References SEFormatBMP::m_dontUpdate, SEFormatJPEG::OptionWidget::m_logger, and SEFormatBMP::settingsChanged().
void SEFormatWAV::OptionWidget::settingsChanged (int value = -1) [protected, slot]
Definition at line 127 of file optionwidget.cpp.
References SEFormatBMP::m_dontUpdate, SEFormatJPEG::OptionWidget::m_logger, SEFormatJPEG::OptionWidget::optionHasChanged(), and SEFormatJPEG::OptionWidget::quality().
Member Data Documentation
bool SEFormatWAV::OptionWidget::m_dontUpdate [private]
Definition at line 34 of file optionwidget.h.
QPointer<Logger> SEFormatWAV::OptionWidget::m_logger [private]
Definition at line 30 of file optionwidget.h.
The documentation for this class was generated from the following files:
modules/seformatwav/optionwidget.h
modules/seformatwav/optionwidget.cpp