SilentEye: SilentEye::MainWindow Class Reference
SilentEye::MainWindow Class Reference
The main window of SilentEye.
#include <mainwindow.h>
Public Member Functions
MainWindow (QString url="", QWidget *parent=0)
~MainWindow ()
Private Slots
void dragEnterEvent (QDragEnterEvent *)
void dropEvent (QDropEvent *)
void closeCurrentTab ()
void addMediaTab (QPointer< Media >)
void paste ()
void copy ()
void execDecodeDialog ()
void execEncodeDialog ()
void execPropertyDialog ()
void execUpdateDialog ()
void newMedia (QString)
void openFile ()
void playMedia ()
void stopMedia ()
Private Member Functions
void connectSignals ()
void setEnabledImageActions (const bool value)
QPointer< Media > currentMedia ()
void closeTabByPath (QString)
Private Attributes
EncodeDialog encodeDialog
PropertyDialog propertyDialog
DecodeDialog decodeDialog
PreferenceDialog preferenceDialog
AboutDialog aboutDialog
UpdateDialog updateDialog
QMenu * contextMenu
QPushButton * closeTabButton
QMap< QString, QPointer< Media > > m_mediaMap
bool m_hasMediaLoaded
QPointer< QSound > m_currentSound
QPointer< Logger > m_logger
Detailed Description
The main window of SilentEye.
Definition at line 36 of file mainwindow.h.
Constructor & Destructor Documentation
SilentEye::MainWindow::MainWindow (QString url = "", QWidget * parent = 0)
Definition at line 23 of file mainwindow.cpp.
References connectSignals(), m_hasMediaLoaded, m_logger, newMedia(), and SEFormatBMP::setupUi().
SilentEye::MainWindow::~MainWindow ()
Definition at line 43 of file mainwindow.cpp.
References contextMenu, m_currentSound, and m_logger.
Member Function Documentation
void SilentEye::MainWindow::addMediaTab (QPointer< Media > md) [private, slot]
Definition at line 51 of file mainwindow.cpp.
References closeTabButton, closeTabByPath(), SilentEye::connect(), contextMenu, m_hasMediaLoaded, m_mediaMap, playMedia(), setEnabledImageActions(), SilentEye::MediaWidget::setPixmap(), and stopMedia().
Referenced by newMedia(), and paste().
void SilentEye::MainWindow::closeCurrentTab () [private, slot]
Definition at line 96 of file mainwindow.cpp.
References closeTabButton, m_currentSound, m_hasMediaLoaded, and setEnabledImageActions().
Referenced by connectSignals().
void SilentEye::MainWindow::closeTabByPath (QString path) [private]
Definition at line 116 of file mainwindow.cpp.
References m_currentSound, and m_mediaMap.
Referenced by addMediaTab().
void SilentEye::MainWindow::connectSignals () [private]
Definition at line 345 of file mainwindow.cpp.
References aboutDialog, closeCurrentTab(), closeTabButton, SilentEye::connect(), contextMenu, copy(), encodeDialog, execDecodeDialog(), execEncodeDialog(), execPropertyDialog(), execUpdateDialog(), newMedia(), openFile(), paste(), and preferenceDialog.
Referenced by MainWindow().
void SilentEye::MainWindow::copy () [private, slot]
Definition at line 263 of file mainwindow.cpp.
References currentMedia(), and m_hasMediaLoaded.
Referenced by connectSignals().
QPointer< Media > SilentEye::MainWindow::currentMedia () [private]
Definition at line 179 of file mainwindow.cpp.
References m_mediaMap.
Referenced by copy(), execDecodeDialog(), execEncodeDialog(), execPropertyDialog(), playMedia(), and stopMedia().
void SilentEye::MainWindow::dragEnterEvent (QDragEnterEvent * event) [private, slot]
Definition at line 154 of file mainwindow.cpp.
void SilentEye::MainWindow::dropEvent (QDropEvent * event) [private, slot]
Definition at line 160 of file mainwindow.cpp.
References newMedia().
void SilentEye::MainWindow::execDecodeDialog () [private, slot]
Definition at line 329 of file mainwindow.cpp.
References currentMedia(), decodeDialog, m_currentSound, and SilentEye::OptionDialog::setMedia().
Referenced by connectSignals().
void SilentEye::MainWindow::execEncodeDialog () [private, slot]
Definition at line 318 of file mainwindow.cpp.
References currentMedia(), encodeDialog, m_currentSound, and SilentEye::OptionDialog::setMedia().
Referenced by connectSignals().
void SilentEye::MainWindow::execPropertyDialog () [private, slot]
Definition at line 312 of file mainwindow.cpp.
References currentMedia(), propertyDialog, and SilentEye::PropertyDialog::setMedia().
Referenced by connectSignals().
void SilentEye::MainWindow::execUpdateDialog () [private, slot]
Definition at line 340 of file mainwindow.cpp.
References updateDialog.
Referenced by connectSignals().
void SilentEye::MainWindow::newMedia (QString url) [private, slot]
Definition at line 188 of file mainwindow.cpp.
References addMediaTab(), SilentEyeFramework::SilentEyeException::details(), m_logger, and SilentEyeFramework::SilentEyeException::message().
Referenced by connectSignals(), dropEvent(), MainWindow(), and openFile().
void SilentEye::MainWindow::openFile () [private, slot]
Definition at line 229 of file mainwindow.cpp.
References SilentEye::Controller::instance(), and newMedia().
Referenced by connectSignals().
void SilentEye::MainWindow::paste () [private, slot]
Definition at line 248 of file mainwindow.cpp.
References addMediaTab().
Referenced by connectSignals().
void SilentEye::MainWindow::playMedia () [private, slot]
Definition at line 279 of file mainwindow.cpp.
References currentMedia(), SilentEyeFramework::Media::filePath(), m_currentSound, m_hasMediaLoaded, and SilentEyeFramework::Media::type().
Referenced by addMediaTab().
void SilentEye::MainWindow::setEnabledImageActions (const bool value) [private]
Definition at line 141 of file mainwindow.cpp.
Referenced by addMediaTab(), and closeCurrentTab().
void SilentEye::MainWindow::stopMedia () [private, slot]
Definition at line 301 of file mainwindow.cpp.
References currentMedia(), m_currentSound, m_hasMediaLoaded, and SilentEyeFramework::Media::type().
Referenced by addMediaTab().
Member Data Documentation
AboutDialog SilentEye::MainWindow::aboutDialog [private]
Definition at line 45 of file mainwindow.h.
Referenced by connectSignals().
QPushButton* SilentEye::MainWindow::closeTabButton [private]
Definition at line 49 of file mainwindow.h.
Referenced by addMediaTab(), closeCurrentTab(), and connectSignals().
QMenu* SilentEye::MainWindow::contextMenu [private]
Definition at line 48 of file mainwindow.h.
Referenced by addMediaTab(), connectSignals(), and ~MainWindow().
DecodeDialog SilentEye::MainWindow::decodeDialog [private]
Definition at line 43 of file mainwindow.h.
Referenced by execDecodeDialog().
EncodeDialog SilentEye::MainWindow::encodeDialog [private]
Definition at line 38 of file mainwindow.h.
Referenced by connectSignals(), and execEncodeDialog().
QPointer<QSound> SilentEye::MainWindow::m_currentSound [private]
Definition at line 54 of file mainwindow.h.
Referenced by closeCurrentTab(), closeTabByPath(), execDecodeDialog(), execEncodeDialog(), playMedia(), stopMedia(), and ~MainWindow().
bool SilentEye::MainWindow::m_hasMediaLoaded [private]
Definition at line 52 of file mainwindow.h.
Referenced by addMediaTab(), closeCurrentTab(), copy(), MainWindow(), playMedia(), and stopMedia().
QPointer<Logger> SilentEye::MainWindow::m_logger [private]
Definition at line 56 of file mainwindow.h.
Referenced by MainWindow(), newMedia(), and ~MainWindow().
QMap<QString, QPointer<Media> > SilentEye::MainWindow::m_mediaMap [private]
Definition at line 51 of file mainwindow.h.
Referenced by addMediaTab(), closeTabByPath(), and currentMedia().
PreferenceDialog SilentEye::MainWindow::preferenceDialog [private]
Definition at line 44 of file mainwindow.h.
Referenced by connectSignals().
PropertyDialog SilentEye::MainWindow::propertyDialog [private]
Definition at line 42 of file mainwindow.h.
Referenced by execPropertyDialog().
UpdateDialog SilentEye::MainWindow::updateDialog [private]
Definition at line 46 of file mainwindow.h.
Referenced by execUpdateDialog().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp