SilentEye: SilentEye Namespace Reference
SilentEye Namespace Reference
SilentEye application GUI.
Classes
class AboutDialog
Display information about SilentEye (author, copyright, ...)
class Controller
Manage HTTP proxy and application path (singleton)
class DecodeDialog
Dialog for generic decoding process.
class EncodeDialog
Dialog for generic encoding process.
class MainWindow
The main window of SilentEye.
class MediaWidget
Manage media view into main window.
class ModuleManager
Load and manage SilentEye's Plug-ins.
class OptionDialog
Mother class for encode and decode dialog.
class PreferenceDialog
Preference/configuration dialog.
class PropertyDialog
Show current media properties.
class UpdateDialog
Check for new version of SilentEye (HTTP)
Functions
m_logger setClassName ("DecodeDialog")
this setWindowTitle ("Decode message")
this setWindowIcon (QPixmap(QString::fromUtf8(":/icons/img/decode.png")))
okButton setText ("Decode")
iconLabel setPixmap (QPixmap(QString::fromUtf8(":/icons/img/decode.png")))
msgLabel setText ("Decoded message")
fileNameLabel setText ("")
fileButton setEnabled (false)
fileRemoveButton setVisible (false)
compressCheckBox setText ("Compressed data")
cryptoCheckBox setText ("Encrypted data")
msgTextEdit setReadOnly (true)
updateDialogSize ()
connect (fileButton, SIGNAL(clicked(bool)), this, SLOT(selectFile()))
m_logger setClassName ("EncodeDialog")
this setWindowTitle ("Encode message")
this setWindowIcon (QPixmap(QString::fromUtf8(":/icons/img/encode.png")))
okButton setText ("Encode")
iconLabel setPixmap (QPixmap(QString::fromUtf8(":/icons/img/encode.png")))
msgLabel setText ("Write a message or select a file to hide.")
connect (fileButton, SIGNAL(pressed()), this, SLOT(selectFile()))
Variables
F __pad0__
m_checkSize = false
Detailed Description
SilentEye application GUI.
Function Documentation
SilentEye::connect (fileButton , SIGNAL(clicked(bool)) , this , SLOT(selectFile()))
Referenced by SilentEye::MainWindow::addMediaTab(), SilentEye::OptionDialog::connectSignals(), SilentEye::MainWindow::connectSignals(), SilentEye::Controller::Controller(), SilentEye::OptionDialog::currentFormatModule(), SilentEye::UpdateDialog::download(), SilentEye::MediaWidget::MediaWidget(), SilentEye::PreferenceDialog::PreferenceDialog(), and SilentEye::PropertyDialog::PropertyDialog().
SilentEye::connect (fileButton , SIGNAL(pressed()) , this , SLOT(selectFile()))
m_logger SilentEye::setClassName ("DecodeDialog")
m_logger SilentEye::setClassName ("EncodeDialog")
fileButton SilentEye::setEnabled (false)
iconLabel SilentEye::setPixmap (QPixmap(QString::fromUtf8(":/icons/img/decode.png")))
iconLabel SilentEye::setPixmap (QPixmap(QString::fromUtf8(":/icons/img/encode.png")))
msgTextEdit SilentEye::setReadOnly (true)
fileNameLabel SilentEye::setText ("")
compressCheckBox SilentEye::setText ("Compressed data")
okButton SilentEye::setText ("Decode")
cryptoCheckBox SilentEye::setText ("Encrypted data")
msgLabel SilentEye::setText ("Write a message or select a file to hide.")
msgLabel SilentEye::setText ("Decoded message")
okButton SilentEye::setText ("Encode")
orLabel SilentEye::setVisible (false)
this SilentEye::setWindowIcon (QPixmap(QString::fromUtf8(":/icons/img/encode.png")))
this SilentEye::setWindowIcon (QPixmap(QString::fromUtf8(":/icons/img/decode.png")))
this SilentEye::setWindowTitle ("Decode message")
Referenced by SilentEye::EncodeDialog::showEvent(), and SilentEye::DecodeDialog::showEvent().
this SilentEye::setWindowTitle ("Encode message")
SilentEye::updateDialogSize ()
Variable Documentation
F SilentEye::__pad0__
Definition at line 29 of file decodedialog.cpp.
SilentEye::m_checkSize = false
Definition at line 31 of file decodedialog.cpp.