SilentEye: SilentEyeFramework::SilentEyeException Class Reference
SilentEyeFramework::SilentEyeException Class Reference
Internal exception only used by SilentEyeFramework.
#include <silenteyeexception.h>