SilentEye: SilentEye::Controller Class Reference
SilentEye::Controller Class Reference
Manage HTTP proxy and application path (singleton).
#include <controller.h>
Public Slots
void updateProxySettings ()
Public Member Functions
~Controller ()
Static Public Member Functions
static QPointer< Controller > instance ()
Public Attributes
Config config
QString appPath
QNetworkAccessManager networkManager
Private Slots
void proxyAuthentication (const QNetworkProxy &, QAuthenticator *)
Private Member Functions
Controller (QObject *parent=0)
Private Attributes
QPointer< Logger > m_logger
Static Private Attributes
static QPointer< Controller > m_pointer = NULL
Detailed Description
Manage HTTP proxy and application path (singleton).
Definition at line 31 of file controller.h.
Constructor & Destructor Documentation
SilentEye::Controller::Controller (QObject * parent = 0) [private]
Definition at line 24 of file controller.cpp.
References appPath, m_logger, networkManager, and proxyAuthentication().
Referenced by instance().
SilentEye::Controller::~Controller ()
Definition at line 35 of file controller.cpp.
Member Function Documentation
QPointer< Controller > SilentEye::Controller::instance () [static]
Definition at line 40 of file controller.cpp.
References Controller(), and m_pointer.
Referenced by SilentEye::PreferenceDialog::accepted(), SilentEye::UpdateDialog::download(), SilentEye::OptionDialog::loadEncryptionTypes(), SilentEye::OptionDialog::loadFormats(), SilentEye::MainWindow::openFile(), SilentEye::OptionDialog::selectFile(), SilentEye::OptionDialog::selectFolder(), SilentEye::PreferenceDialog::setConfig(), SilentEye::OptionDialog::setupDialog(), SilentEye::UpdateDialog::showEvent(), and SilentEye::UpdateDialog::UpdateDialog().
void SilentEye::Controller::proxyAuthentication (const QNetworkProxy & proxy, QAuthenticator * authenticator) [private, slot]
Definition at line 61 of file controller.cpp.
References m_logger.
Referenced by Controller().
void SilentEye::Controller::updateProxySettings () [slot]
Definition at line 49 of file controller.cpp.
References config, SilentEyeFramework::Config::get(), and networkManager.
Member Data Documentation
QString SilentEye::Controller::appPath
Definition at line 46 of file controller.h.
Referenced by Controller().
Config SilentEye::Controller::config
Definition at line 45 of file controller.h.
Referenced by updateProxySettings().
QPointer<Logger> SilentEye::Controller::m_logger [private]
Definition at line 38 of file controller.h.
Referenced by Controller(), and proxyAuthentication().
QPointer< Controller > SilentEye::Controller::m_pointer = NULL [static, private]
Definition at line 33 of file controller.h.
Referenced by instance().
QNetworkAccessManager SilentEye::Controller::networkManager
Definition at line 47 of file controller.h.
Referenced by Controller(), and updateProxySettings().
The documentation for this class was generated from the following files:
controller.h
controller.cpp