SilentEye: SilentEye::OptionDialog Class Reference
SilentEye::OptionDialog Class Reference
Mother class for encode and decode dialog.
#include <optiondialog.h>