SilentEye: SilentEye::UpdateDialog Class Reference
SilentEye::UpdateDialog Class Reference
Check for new version of SilentEye (HTTP).
#include <updatedialog.h>
Public Member Functions
UpdateDialog (QWidget *parent=0)
~UpdateDialog ()
Private Slots
void showEvent (QShowEvent *)
void download (QUrl)
void httpReadyRead ()
void httpFinished ()
Private Attributes
QUrl m_url
QNetworkReply * m_reply
QString m_buffer
QPointer< Logger > m_logger
Detailed Description
Check for new version of SilentEye (HTTP).
Definition at line 32 of file updatedialog.h.
Constructor & Destructor Documentation
SilentEye::UpdateDialog::UpdateDialog (QWidget * parent = 0)
Definition at line 23 of file updatedialog.cpp.
References SilentEyeFramework::Config::get(), SilentEye::Controller::instance(), SilentEyeFramework::Config::isLoaded(), and m_logger.
SilentEye::UpdateDialog::~UpdateDialog ()
Definition at line 39 of file updatedialog.cpp.
References m_logger.
Member Function Documentation
void SilentEye::UpdateDialog::download (QUrl url) [private, slot]
Definition at line 56 of file updatedialog.cpp.
References httpFinished(), httpReadyRead(), SilentEye::Controller::instance(), m_buffer, m_reply, and m_url.
Referenced by httpFinished(), and showEvent().
void SilentEye::UpdateDialog::httpFinished () [private, slot]
Definition at line 73 of file updatedialog.cpp.
References download(), SilentEyeFramework::Config::get(), m_buffer, m_logger, m_reply, and m_url.
Referenced by download().
void SilentEye::UpdateDialog::httpReadyRead () [private, slot]
Definition at line 68 of file updatedialog.cpp.
References m_buffer, and m_reply.
Referenced by download().
void SilentEye::UpdateDialog::showEvent (QShowEvent * event) [private, slot]
Definition at line 46 of file updatedialog.cpp.
References download(), and SilentEye::Controller::instance().
Member Data Documentation
QString SilentEye::UpdateDialog::m_buffer [private]
Definition at line 39 of file updatedialog.h.
Referenced by download(), httpFinished(), and httpReadyRead().
QPointer<Logger> SilentEye::UpdateDialog::m_logger [private]
Definition at line 41 of file updatedialog.h.
Referenced by httpFinished(), UpdateDialog(), and ~UpdateDialog().
QNetworkReply* SilentEye::UpdateDialog::m_reply [private]
Definition at line 38 of file updatedialog.h.
Referenced by download(), httpFinished(), and httpReadyRead().
QUrl SilentEye::UpdateDialog::m_url [private]
Definition at line 34 of file updatedialog.h.
Referenced by download(), and httpFinished().
The documentation for this class was generated from the following files:
updatedialog.h
updatedialog.cpp