SilentEye: PropertyDialog Class Reference
PropertyDialog Class Reference
#include <propertydialog.h>
Public Member Functions
PropertyDialog (QWidget *parent=0)
void setImage (Image *img)
Private Attributes
Image * m_img
Detailed Description
Definition at line 25 of file propertydialog.h.
Constructor & Destructor Documentation
PropertyDialog::PropertyDialog (QWidget * parent = 0)
Definition at line 19 of file propertydialog.cpp.
References m_img.
Member Function Documentation
void PropertyDialog::setImage (Image * img)
Definition at line 26 of file propertydialog.cpp.
References SilentEyeFramework::Image::capacity(), SilentEyeFramework::Image::filePath(), ModuleManager::get(), ModuleManager::IMAGEFORMAT, m_img, and SilentEyeFramework::ModuleInterface::typeSupported().
Referenced by MainWindow::execPropertyDialog().
Member Data Documentation
Image* PropertyDialog::m_img [private]
Definition at line 27 of file propertydialog.h.
Referenced by PropertyDialog(), and setImage().
The documentation for this class was generated from the following files:
propertydialog.h
propertydialog.cpp