SilentEye: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
Private Slots
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void closeCurrentTab ()
void addImageTab (Image *img)
void execDecodeDialog ()
void execEncodeDialog ()
void execPropertyDialog ()
void newImage (QString)
void openFile ()
Private Member Functions
void connectSignals ()
void setEnabledImageActions (const bool value)
Image * currentImage ()
void closeTabByName (QString name)
Private Attributes
EncodeDialog encodeDialog
PropertyDialog propertyDialog
DecodeDialog decodeDialog
PreferenceDialog preferenceDialog
AboutDialog aboutDialog
QClipboard * m_clipboard
QMenu * contextMenu
QPushButton * closeTabButton
QMap< QString, Image * > m_imageMap
bool m_hasImageLoaded
Detailed Description
Definition at line 29 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0)
Definition at line 19 of file mainwindow.cpp.
References connectSignals(), and m_hasImageLoaded.
MainWindow::~MainWindow ()
Definition at line 37 of file mainwindow.cpp.
References contextMenu, and m_imageMap.
Member Function Documentation
void MainWindow::addImageTab (Image * img) [private, slot]
Definition at line 46 of file mainwindow.cpp.
References closeTabButton, closeTabByName(), contextMenu, m_hasImageLoaded, m_imageMap, setEnabledImageActions(), and SilentEyeFramework::Image::shortName().
Referenced by newImage().
void MainWindow::closeCurrentTab () [private, slot]
Definition at line 71 of file mainwindow.cpp.
References closeTabButton, m_hasImageLoaded, and setEnabledImageActions().
Referenced by connectSignals().
void MainWindow::closeTabByName (QString name) [private]
Definition at line 86 of file mainwindow.cpp.
References m_imageMap.
Referenced by addImageTab().
void MainWindow::connectSignals () [private]
Definition at line 206 of file mainwindow.cpp.
References aboutDialog, closeCurrentTab(), closeTabButton, contextMenu, encodeDialog, execDecodeDialog(), execEncodeDialog(), execPropertyDialog(), newImage(), openFile(), and preferenceDialog.
Referenced by MainWindow().
Image * MainWindow::currentImage () [private]
Definition at line 142 of file mainwindow.cpp.
References m_imageMap.
Referenced by execDecodeDialog(), execEncodeDialog(), and execPropertyDialog().
void MainWindow::dragEnterEvent (QDragEnterEvent * event) [private, slot]
Definition at line 117 of file mainwindow.cpp.
void MainWindow::dropEvent (QDropEvent * event) [private, slot]
Definition at line 123 of file mainwindow.cpp.
References newImage().
void MainWindow::execDecodeDialog () [private, slot]
Definition at line 200 of file mainwindow.cpp.
References currentImage(), decodeDialog, and OptionDialog::setImage().
Referenced by connectSignals().
void MainWindow::execEncodeDialog () [private, slot]
Definition at line 194 of file mainwindow.cpp.
References currentImage(), encodeDialog, and OptionDialog::setImage().
Referenced by connectSignals().
void MainWindow::execPropertyDialog () [private, slot]
Definition at line 188 of file mainwindow.cpp.
References currentImage(), propertyDialog, and PropertyDialog::setImage().
Referenced by connectSignals().
void MainWindow::newImage (QString url) [private, slot]
Definition at line 151 of file mainwindow.cpp.
References addImageTab().
Referenced by connectSignals(), dropEvent(), and openFile().
void MainWindow::openFile () [private, slot]
Definition at line 169 of file mainwindow.cpp.
References newImage().
Referenced by connectSignals().
void MainWindow::setEnabledImageActions (const bool value) [private]
Definition at line 105 of file mainwindow.cpp.
Referenced by addImageTab(), and closeCurrentTab().
Member Data Documentation
AboutDialog MainWindow::aboutDialog [private]
Definition at line 38 of file mainwindow.h.
Referenced by connectSignals().
QPushButton* MainWindow::closeTabButton [private]
Definition at line 42 of file mainwindow.h.
Referenced by addImageTab(), closeCurrentTab(), and connectSignals().
QMenu* MainWindow::contextMenu [private]
Definition at line 41 of file mainwindow.h.
Referenced by addImageTab(), connectSignals(), and ~MainWindow().
DecodeDialog MainWindow::decodeDialog [private]
Definition at line 36 of file mainwindow.h.
Referenced by execDecodeDialog().
EncodeDialog MainWindow::encodeDialog [private]
Definition at line 31 of file mainwindow.h.
Referenced by connectSignals(), and execEncodeDialog().
QClipboard* MainWindow::m_clipboard [private]
Definition at line 40 of file mainwindow.h.
bool MainWindow::m_hasImageLoaded [private]
Definition at line 45 of file mainwindow.h.
Referenced by addImageTab(), closeCurrentTab(), and MainWindow().
QMap<QString, Image*> MainWindow::m_imageMap [private]
Definition at line 44 of file mainwindow.h.
Referenced by addImageTab(), closeTabByName(), currentImage(), and ~MainWindow().
PreferenceDialog MainWindow::preferenceDialog [private]
Definition at line 37 of file mainwindow.h.
Referenced by connectSignals().
PropertyDialog MainWindow::propertyDialog [private]
Definition at line 35 of file mainwindow.h.
Referenced by execPropertyDialog().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp