SilentEye: EncodeDialog Class Reference
EncodeDialog Class Reference
#include <encodedialog.h>