SilentEye: ModuleManager Class Reference
ModuleManager Class Reference
#include <modulemanager.h>
Public Types
enum Category { IMAGEFORMAT, CRYPTO, C_UNDEF }
Static Public Member Functions
static QList< ModuleInterface * > & getList ()
static QMap< QString,
ModuleInterface * > & get (Category cat)
static ModuleInterface * get (Category cat, QString type)
static Category getCategory (ModuleInterface *)
static int count ()
static int count (Category cat)
static void load ()
Static Private Attributes
static Logger m_logger
static QMap< Category, QMap
< QString, ModuleInterface * > > m_modulesMap
static QMap< QString,
ModuleInterface * > m_emptyMap
static QList< ModuleInterface * > m_modulesList
Detailed Description
Definition at line 27 of file modulemanager.h.
Member Enumeration Documentation
enum ModuleManager::Category
Enumerator:
IMAGEFORMAT
CRYPTO
C_UNDEF
Definition at line 30 of file modulemanager.h.
Member Function Documentation
int ModuleManager::count () [static]
Definition at line 66 of file modulemanager.cpp.
References m_modulesList.
Referenced by count(), PreferenceDialog::PreferenceDialog(), and OptionDialog::setupDialog().
int ModuleManager::count (Category cat) [static]
Definition at line 72 of file modulemanager.cpp.
References count(), and m_modulesMap.
QMap< QString, ModuleInterface * > & ModuleManager::get (Category cat) [static]
Definition at line 30 of file modulemanager.cpp.
References m_emptyMap, and m_modulesMap.
Referenced by OptionDialog::currentCryptoModule(), OptionDialog::currentFormatModule(), OptionDialog::imageFormatChanged(), OptionDialog::loadEncryptionTypes(), OptionDialog::loadImageFormats(), and PropertyDialog::setImage().
ModuleInterface * ModuleManager::get (Category cat, QString type) [static]
Definition at line 39 of file modulemanager.cpp.
References m_modulesMap.
ModuleManager::Category ModuleManager::getCategory (ModuleInterface * module) [static]
Definition at line 47 of file modulemanager.cpp.
References m_modulesMap.
Referenced by PreferenceDialog::PreferenceDialog().
QList< ModuleInterface * > & ModuleManager::getList () [static]
Definition at line 24 of file modulemanager.cpp.
References m_modulesList.
Referenced by PreferenceDialog::PreferenceDialog().
void ModuleManager::load () [static]
Definition at line 79 of file modulemanager.cpp.
References m_logger, m_modulesList, m_modulesMap, SilentEyeFramework::ModuleInterface::typeSupported(), and SilentEyeFramework::Logger::warning().
Referenced by main().
Member Data Documentation
QMap< QString, ModuleInterface * > ModuleManager::m_emptyMap [static, private]
Definition at line 35 of file modulemanager.h.
Referenced by get().
Logger ModuleManager::m_logger [static, private]
Definition at line 33 of file modulemanager.h.
Referenced by load().
QList< ModuleInterface * > ModuleManager::m_modulesList [static, private]
Definition at line 36 of file modulemanager.h.
Referenced by count(), getList(), and load().
QMap< ModuleManager::Category, QMap< QString, ModuleInterface * > > ModuleManager::m_modulesMap [static, private]
Definition at line 34 of file modulemanager.h.
Referenced by count(), get(), getCategory(), and load().
The documentation for this class was generated from the following files:
modulemanager.h
modulemanager.cpp