SilentEye: SilentEyeFramework::ModuleException Class Reference
SilentEyeFramework::ModuleException Class Reference
#include <moduleexception.h>
Public Member Functions
ModuleException (const QString &message) throw ()
ModuleException (const QString &message, const QString &details) throw ()
ModuleException (const ModuleException &exception) throw ()
~ModuleException () throw ()
QString message () const
QString details () const
void raise () const
Exception * clone () const
Private Attributes
QString m_message
QString m_details
Detailed Description
Definition at line 23 of file moduleexception.h.
Constructor & Destructor Documentation
SilentEyeFramework::ModuleException::ModuleException (const QString & message) throw ()
Definition at line 20 of file moduleexception.cpp.
Referenced by clone().
SilentEyeFramework::ModuleException::ModuleException (const QString & message, const QString & details) throw ()
Definition at line 26 of file moduleexception.cpp.
SilentEyeFramework::ModuleException::ModuleException (const ModuleException & exception) throw ()
Definition at line 33 of file moduleexception.cpp.
SilentEyeFramework::ModuleException::~ModuleException () throw ()
Definition at line 39 of file moduleexception.cpp.
Member Function Documentation
Exception* SilentEyeFramework::ModuleException::clone () const [inline]
Definition at line 40 of file moduleexception.h.
References ModuleException().
QString SilentEyeFramework::ModuleException::details () const
Definition at line 45 of file moduleexception.cpp.
References m_details.
Referenced by OptionDialog::displayModuleException().
QString SilentEyeFramework::ModuleException::message () const
Definition at line 41 of file moduleexception.cpp.
References m_message.
Referenced by OptionDialog::displayModuleException().
void SilentEyeFramework::ModuleException::raise () const [inline]
Definition at line 39 of file moduleexception.h.
Member Data Documentation
QString SilentEyeFramework::ModuleException::m_details [private]
Definition at line 27 of file moduleexception.h.
Referenced by details().
QString SilentEyeFramework::ModuleException::m_message [private]
Definition at line 26 of file moduleexception.h.
Referenced by message().
The documentation for this class was generated from the following files:
sef/moduleexception.h
sef/moduleexception.cpp