SilentEye: Controller Class Reference
Controller Class Reference
#include <controller.h>
Static Public Attributes
static QString appPath = QString("/")
static Config config = Config()
Detailed Description
Definition at line 23 of file controller.h.
Member Data Documentation
QString Controller::appPath = QString("/") [static]
Definition at line 27 of file controller.h.
Referenced by main().
Config Controller::config = Config() [static]
Definition at line 28 of file controller.h.
Referenced by PreferenceDialog::accepted(), OptionDialog::loadEncryptionTypes(), OptionDialog::loadImageFormats(), main(), PreferenceDialog::setConfig(), OptionDialog::setupDialog(), and EncodeDialog::showEvent().
The documentation for this class was generated from the following files:
controller.h
controller.cpp