SilentEye: ImageWidget Class Reference
ImageWidget Class Reference
#include <imagewidget.h>
Public Member Functions
ImageWidget (QWidget *parent=0)
void setPixmap (const QPixmap pix)
void setContextMenu (QMenu *menu)
void contextMenuEvent (QContextMenuEvent *event)
void updateImageSize ()
void resizeEvent (QResizeEvent *event)
Private Attributes
QMenu * m_menu
QSize m_size
bool m_hasImg
Detailed Description
Definition at line 25 of file imagewidget.h.
Constructor & Destructor Documentation
ImageWidget::ImageWidget (QWidget * parent = 0) [inline]
Definition at line 33 of file imagewidget.h.
References m_hasImg, and m_menu.
Member Function Documentation
void ImageWidget::contextMenuEvent (QContextMenuEvent * event) [inline]
Definition at line 53 of file imagewidget.h.
References m_menu.
void ImageWidget::resizeEvent (QResizeEvent * event) [inline]
Definition at line 88 of file imagewidget.h.
References updateImageSize().
void ImageWidget::setContextMenu (QMenu * menu) [inline]
Definition at line 48 of file imagewidget.h.
References m_menu.
void ImageWidget::setPixmap (const QPixmap pix) [inline]
Definition at line 40 of file imagewidget.h.
References m_hasImg, m_size, and updateImageSize().
void ImageWidget::updateImageSize () [inline]
Definition at line 59 of file imagewidget.h.
References m_hasImg, and m_size.
Referenced by resizeEvent(), and setPixmap().
Member Data Documentation
bool ImageWidget::m_hasImg [private]
Definition at line 30 of file imagewidget.h.
Referenced by ImageWidget(), setPixmap(), and updateImageSize().
QMenu* ImageWidget::m_menu [private]
Definition at line 28 of file imagewidget.h.
Referenced by contextMenuEvent(), ImageWidget(), and setContextMenu().
QSize ImageWidget::m_size [private]
Definition at line 29 of file imagewidget.h.
Referenced by setPixmap(), and updateImageSize().
The documentation for this class was generated from the following file:
imagewidget.h