SilentEye: SEFormatBMP::SEFormatBmp Class Reference
SEFormatBMP::SEFormatBmp Class Reference
Official module for support of BMP image (using LSB)
#include <seformatbmp.h>
Signals
void optionChanged ()
Public Member Functions
SEFormatBmp ()
~SEFormatBmp ()
QWidget * encodeWidget ()
QWidget * decodeWidget ()
bool isEncodeWidgetReady () const
bool isDecodeWidgetReady () const
QPointer< Image > encodeImage (QPointer< Image >, bool=false)
QPointer< Image > decodeImage (QPointer< Image >, bool=false)
QString typeSupported () const
Type supported (ex: BMP, JPEG, AES128, etc.)
QString name () const
Plug-in name (ex: FooBar)
QString version () const
Plug-in version (ex: 1.2.0)
QString status ()
Current status of the module (ex: KO|qca2-plugin-ossl missing)
Private Slots
void optionHasChanged ()
Private Member Functions
Q_INTERFACES (SilentEyeFramework::ImageModuleInterface)
QPointer< Image > updateImage (QPointer< Image >, OptionWidget *, bool)
Private Attributes
QPointer< Logger > m_logger
OptionWidget * m_encodeWidget
OptionWidget * m_decodeWidget
Detailed Description
Official module for support of BMP image (using LSB)
Definition at line 32 of file seformatbmp.h.
Constructor & Destructor Documentation
SEFormatBMP::SEFormatBmp::SEFormatBmp ()
SEFormatBMP::SEFormatBmp::~SEFormatBmp ()
Definition at line 30 of file seformatbmp.cpp.
References m_decodeWidget, m_encodeWidget, and m_logger.
Member Function Documentation
QPointer< Image > SEFormatBMP::SEFormatBmp::decodeImage (QPointer< Image > img, bool dontDuplicate = false) [virtual]
Implements SilentEyeFramework::ImageModuleInterface.
Definition at line 81 of file seformatbmp.cpp.
References decodeWidget(), and updateImage().
QWidget * SEFormatBMP::SEFormatBmp::decodeWidget () [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 65 of file seformatbmp.cpp.
References m_decodeWidget.
Referenced by decodeImage().
QPointer< Image > SEFormatBMP::SEFormatBmp::encodeImage (QPointer< Image > img, bool dontDuplicate = false) [virtual]
Implements SilentEyeFramework::ImageModuleInterface.
Definition at line 75 of file seformatbmp.cpp.
References encodeWidget(), and updateImage().
QWidget * SEFormatBMP::SEFormatBmp::encodeWidget () [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 54 of file seformatbmp.cpp.
References SEFormatBMP::connect(), m_encodeWidget, and optionHasChanged().
Referenced by encodeImage().
bool SEFormatBMP::SEFormatBmp::isDecodeWidgetReady () const [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 118 of file seformatbmp.cpp.
bool SEFormatBMP::SEFormatBmp::isEncodeWidgetReady () const [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 113 of file seformatbmp.cpp.
QString SEFormatBMP::SEFormatBmp::name () const [virtual]
Plug-in name (ex: FooBar)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 39 of file seformatbmp.cpp.
void SEFormatBMP::SEFormatBmp::optionChanged () [signal]
Reimplemented from SilentEyeFramework::FormatModuleInterface.
Referenced by optionHasChanged().
void SEFormatBMP::SEFormatBmp::optionHasChanged () [private, slot]
Definition at line 123 of file seformatbmp.cpp.
References optionChanged().
Referenced by encodeWidget().
SEFormatBMP::SEFormatBmp::Q_INTERFACES (SilentEyeFramework::ImageModuleInterface) [private]
QString SEFormatBMP::SEFormatBmp::status () [virtual]
Current status of the module (ex: KO|qca2-plugin-ossl missing)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 49 of file seformatbmp.cpp.
QString SEFormatBMP::SEFormatBmp::typeSupported () const [virtual]
Type supported (ex: BMP, JPEG, AES128, etc.)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 108 of file seformatbmp.cpp.
QPointer< Image > SEFormatBMP::SEFormatBmp::updateImage (QPointer< Image > img, OptionWidget * w, bool dontDuplicate) [private]
Definition at line 87 of file seformatbmp.cpp.
References SEFormatBMP::OptionWidget::distribution(), SEFormatBMP::OptionWidget::headerPosition(), SEFormatBMP::OptionWidget::isBlueUsed(), SEFormatBMP::OptionWidget::isGreenUsed(), SEFormatBMP::OptionWidget::isRedUsed(), SEFormatBMP::OptionWidget::nbBits(), SEFormatBMP::ImageBMP::setColorUsed(), SEFormatBMP::ImageBMP::setDistribution(), SEFormatBMP::ImageBMP::setHeaderPosition(), and SEFormatBMP::ImageBMP::setNbBits().
Referenced by decodeImage(), and encodeImage().
QString SEFormatBMP::SEFormatBmp::version () const [virtual]
Plug-in version (ex: 1.2.0)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 44 of file seformatbmp.cpp.
Member Data Documentation
OptionWidget* SEFormatBMP::SEFormatBmp::m_decodeWidget [private]
Definition at line 40 of file seformatbmp.h.
Referenced by decodeWidget(), and ~SEFormatBmp().
OptionWidget* SEFormatBMP::SEFormatBmp::m_encodeWidget [private]
Definition at line 39 of file seformatbmp.h.
Referenced by encodeWidget(), and ~SEFormatBmp().
QPointer<Logger> SEFormatBMP::SEFormatBmp::m_logger [private]
Definition at line 38 of file seformatbmp.h.
Referenced by ~SEFormatBmp().
The documentation for this class was generated from the following files:
modules/seformatbmp/seformatbmp.h
modules/seformatbmp/seformatbmp.cpp