SilentEye: SEFormatWAV::SEFormatWav Class Reference
SEFormatWAV::SEFormatWav Class Reference
Official module for support of WAVE/PCM sound (using LSB)
#include <seformatwav.h>
Signals
void optionChanged ()
Public Member Functions
SEFormatWav ()
~SEFormatWav ()
QWidget * encodeWidget ()
QWidget * decodeWidget ()
bool isEncodeWidgetReady () const
bool isDecodeWidgetReady () const
QPointer< Audio > encodeAudio (QPointer< Audio >, bool=false)
QPointer< Audio > decodeAudio (QPointer< Audio >, bool=false)
QString typeSupported () const
QString name () const
QString version () const
QString status ()
Private Slots
void optionHasChanged ()
Private Member Functions
Q_INTERFACES (SilentEyeFramework::AudioModuleInterface)
QPointer< Audio > updateAudio (QPointer< Audio >, OptionWidget *, bool)
Private Attributes
QPointer< Logger > m_logger
OptionWidget * m_encodeWidget
OptionWidget * m_decodeWidget
Detailed Description
Official module for support of WAVE/PCM sound (using LSB)
Definition at line 32 of file seformatwav.h.
Constructor & Destructor Documentation
SEFormatWAV::SEFormatWav::SEFormatWav ()
SEFormatWAV::SEFormatWav::~SEFormatWav ()
Definition at line 30 of file seformatwav.cpp.
References m_decodeWidget, m_encodeWidget, and m_logger.
Member Function Documentation
QPointer< Audio > SEFormatWAV::SEFormatWav::decodeAudio (QPointer< Audio > audio, bool dontDuplicate = false)
Definition at line 80 of file seformatwav.cpp.
References decodeWidget(), and updateAudio().
QWidget * SEFormatWAV::SEFormatWav::decodeWidget ()
Definition at line 65 of file seformatwav.cpp.
References m_decodeWidget.
Referenced by decodeAudio().
QPointer< Audio > SEFormatWAV::SEFormatWav::encodeAudio (QPointer< Audio > audio, bool dontDuplicate = false)
Definition at line 75 of file seformatwav.cpp.
References encodeWidget(), and updateAudio().
QWidget * SEFormatWAV::SEFormatWav::encodeWidget ()
Definition at line 54 of file seformatwav.cpp.
References SEFormatWAV::connect(), m_encodeWidget, and optionHasChanged().
Referenced by encodeAudio().
bool SEFormatWAV::SEFormatWav::isDecodeWidgetReady () const
Definition at line 118 of file seformatwav.cpp.
bool SEFormatWAV::SEFormatWav::isEncodeWidgetReady () const
Definition at line 113 of file seformatwav.cpp.
QString SEFormatWAV::SEFormatWav::name () const
Definition at line 39 of file seformatwav.cpp.
void SEFormatWAV::SEFormatWav::optionChanged () [signal]
Referenced by optionHasChanged().
void SEFormatWAV::SEFormatWav::optionHasChanged () [private, slot]
Definition at line 123 of file seformatwav.cpp.
References optionChanged().
Referenced by encodeWidget().
SEFormatWAV::SEFormatWav::Q_INTERFACES (SilentEyeFramework::AudioModuleInterface) [private]
QString SEFormatWAV::SEFormatWav::status ()
Definition at line 49 of file seformatwav.cpp.
QString SEFormatWAV::SEFormatWav::typeSupported () const
Definition at line 108 of file seformatwav.cpp.
QPointer< Audio > SEFormatWAV::SEFormatWav::updateAudio (QPointer< Audio > aud, OptionWidget * w, bool dontDuplicate) [private]
Definition at line 85 of file seformatwav.cpp.
References SEFormatWAV::OptionWidget::channels(), SEFormatWAV::OptionWidget::distribution(), SEFormatWAV::OptionWidget::headerPosition(), SEFormatWAV::OptionWidget::nbBits(), SEFormatWAV::AudioWav::setDistribution(), SEFormatWAV::AudioWav::setHeaderPosition(), SEFormatWAV::AudioWav::setNbBitsUsed(), and SEFormatWAV::AudioWav::setNbChannelUsed().
Referenced by decodeAudio(), and encodeAudio().
QString SEFormatWAV::SEFormatWav::version () const
Definition at line 44 of file seformatwav.cpp.
Member Data Documentation
OptionWidget* SEFormatWAV::SEFormatWav::m_decodeWidget [private]
Definition at line 40 of file seformatwav.h.
Referenced by decodeWidget(), and ~SEFormatWav().
OptionWidget* SEFormatWAV::SEFormatWav::m_encodeWidget [private]
Definition at line 39 of file seformatwav.h.
Referenced by encodeWidget(), and ~SEFormatWav().
QPointer<Logger> SEFormatWAV::SEFormatWav::m_logger [private]
Definition at line 38 of file seformatwav.h.
Referenced by ~SEFormatWav().
The documentation for this class was generated from the following files:
modules/seformatwav/seformatwav.h
modules/seformatwav/seformatwav.cpp