SilentEye: SilentEye::MediaWidget Class Reference
SilentEye::MediaWidget Class Reference
Manage media view into main window.
#include <mediawidget.h>
Signals
void play ()
void stop ()
Public Member Functions
MediaWidget (QWidget *parent=0, QString filepath="")
~MediaWidget ()
void setPixmap (const QPixmap, bool=true)
void setText (const QString)
void setFilepath (const QString)
void setContextMenu (QMenu *)
void showPlayer (bool)
void contextMenuEvent (QContextMenuEvent *)
QString filepath () const
void updateImageSize ()
void resizeEvent (QResizeEvent *)
Private Slots
void playPressed ()
void stopPressed ()
Private Attributes
QMenu * m_menu
QSize m_size
bool m_hasImg
QString m_filepath
Detailed Description
Manage media view into main window.
Definition at line 29 of file mediawidget.h.
Constructor & Destructor Documentation
SilentEye::MediaWidget::MediaWidget (QWidget * parent = 0, QString filepath = "")
Definition at line 20 of file mediawidget.cpp.
References SilentEye::connect(), m_hasImg, m_menu, playPressed(), setFilepath(), SEFormatBMP::setupUi(), and stopPressed().
SilentEye::MediaWidget::~MediaWidget ()
Definition at line 33 of file mediawidget.cpp.
Member Function Documentation
void SilentEye::MediaWidget::contextMenuEvent (QContextMenuEvent * event)
Definition at line 75 of file mediawidget.cpp.
References m_menu.
QString SilentEye::MediaWidget::filepath () const
Definition at line 65 of file mediawidget.cpp.
References m_filepath.
void SilentEye::MediaWidget::play () [signal]
Referenced by playPressed().
void SilentEye::MediaWidget::playPressed () [private, slot]
Definition at line 116 of file mediawidget.cpp.
References play().
Referenced by MediaWidget().
void SilentEye::MediaWidget::resizeEvent (QResizeEvent * event)
Definition at line 110 of file mediawidget.cpp.
References updateImageSize().
void SilentEye::MediaWidget::setContextMenu (QMenu * menu)
Definition at line 60 of file mediawidget.cpp.
References m_menu.
void SilentEye::MediaWidget::setFilepath (const QString path)
Definition at line 48 of file mediawidget.cpp.
References m_filepath.
Referenced by MediaWidget().
void SilentEye::MediaWidget::setPixmap (const QPixmap pix, bool autosize = true)
Definition at line 37 of file mediawidget.cpp.
References m_hasImg, m_size, and updateImageSize().
Referenced by SilentEye::MainWindow::addMediaTab().
void SilentEye::MediaWidget::setText (const QString text)
Definition at line 54 of file mediawidget.cpp.
References m_hasImg.
void SilentEye::MediaWidget::showPlayer (bool value)
Definition at line 70 of file mediawidget.cpp.
void SilentEye::MediaWidget::stop () [signal]
Referenced by stopPressed().
void SilentEye::MediaWidget::stopPressed () [private, slot]
Definition at line 121 of file mediawidget.cpp.
References stop().
Referenced by MediaWidget().
void SilentEye::MediaWidget::updateImageSize ()
Definition at line 81 of file mediawidget.cpp.
References m_hasImg, and m_size.
Referenced by resizeEvent(), and setPixmap().
Member Data Documentation
QString SilentEye::MediaWidget::m_filepath [private]
Definition at line 37 of file mediawidget.h.
Referenced by filepath(), and setFilepath().
bool SilentEye::MediaWidget::m_hasImg [private]
Definition at line 36 of file mediawidget.h.
Referenced by MediaWidget(), setPixmap(), setText(), and updateImageSize().
QMenu* SilentEye::MediaWidget::m_menu [private]
Definition at line 31 of file mediawidget.h.
Referenced by contextMenuEvent(), MediaWidget(), and setContextMenu().
QSize SilentEye::MediaWidget::m_size [private]
Definition at line 35 of file mediawidget.h.
Referenced by setPixmap(), and updateImageSize().
The documentation for this class was generated from the following files:
mediawidget.h
mediawidget.cpp