SilentEye: SilentEye::DecodeDialog Class Reference
SilentEye::DecodeDialog Class Reference
Dialog for generic decoding process.
#include <decodedialog.h>
Public Member Functions
DecodeDialog (QWidget *parent=0)
~DecodeDialog ()
Protected Member Functions
QWidget * currentFormatWidget (FormatModuleInterface *)
Private Slots
void ok ()
void showEvent (QShowEvent *)
void releaseFileButton ()
Detailed Description
Dialog for generic decoding process.
Definition at line 27 of file decodedialog.h.
Constructor & Destructor Documentation
SilentEye::DecodeDialog::DecodeDialog (QWidget * parent = 0)
SilentEye::DecodeDialog::~DecodeDialog ()
Definition at line 56 of file decodedialog.cpp.
Member Function Documentation
QWidget * SilentEye::DecodeDialog::currentFormatWidget (FormatModuleInterface * module) [protected, virtual]
Implements SilentEye::OptionDialog.
Definition at line 78 of file decodedialog.cpp.
References SilentEyeFramework::FormatModuleInterface::decodeWidget().
void SilentEye::DecodeDialog::ok () [private, virtual, slot]
Implements SilentEye::OptionDialog.
Definition at line 86 of file decodedialog.cpp.
References SilentEye::OptionDialog::currentCryptoModule(), SilentEye::OptionDialog::currentFormatModule(), SilentEyeFramework::CryptoModuleInterface::decode(), SilentEyeFramework::decodeAudio(), SilentEye::OptionDialog::displayException(), SilentEyeFramework::FormatModuleInterface::isDecodeWidgetReady(), SilentEye::OptionDialog::isDialogReady(), SilentEye::OptionDialog::m_filePath, SilentEye::OptionDialog::m_logger, SilentEye::OptionDialog::m_md, SilentEyeFramework::ModuleInterface::name(), SilentEye::OptionDialog::removeFile(), and SilentEye::OptionDialog::updateDialogSize().
void SilentEye::DecodeDialog::releaseFileButton () [private, slot]
Definition at line 183 of file decodedialog.cpp.
References SilentEye::OptionDialog::m_filePath.
void SilentEye::DecodeDialog::showEvent (QShowEvent * event) [private, slot]
Definition at line 60 of file decodedialog.cpp.
References SilentEye::OptionDialog::checkCryptoPassword(), SilentEye::OptionDialog::formatChanged(), SilentEye::OptionDialog::m_md, SilentEye::OptionDialog::removeFile(), SilentEye::setWindowTitle(), and SilentEye::OptionDialog::updateDialogSize().
The documentation for this class was generated from the following files:
decodedialog.h
decodedialog.cpp