SilentEye: SEFormatJPEG Namespace Reference
SEFormatJPEG Namespace Reference
SilentEye official module for support of JPEG image.
Classes
class PixelGroup
The pixel group wich represent a block. (8x8 in the Jpeg format)
class GroupedImage
This class reprensents the image where pixels are grouped in square blocs.
class ImageJPEG
JPEG image representation.
class OptionWidget
Widget given to SilentEye main application in order to configure plugin.
class SEFormatJpeg
Official module for support of JPEG image (using LSB)
class StegoTable
Manage the K stegano tables and the index table.
class YCbCr
Manage the YCbCr value for a color corresponding to a pixel (Y: luminance, Cb: blue difference, Cr: red difference)
Functions
connect (pwdCheckBox, SIGNAL(stateChanged(int)), this, SLOT(pwdStateChange(int)))
m_encodeWidget setObjectName ("EncodeWidget")
m_decodeWidget setObjectName ("DecodeWidget")
connect (m_encodeWidget, SIGNAL(optionHasChanged()), this, SLOT(optionHasChanged()))
Variables
F __pad0__
m_logger = new Logger(this)
m_encodeWidget = NULL
m_decodeWidget = NULL
Detailed Description
SilentEye official module for support of JPEG image.
Function Documentation
SEFormatJPEG::connect (pwdCheckBox , SIGNAL(stateChanged(int)) , this , SLOT(pwdStateChange(int)))
Referenced by SEFormatJPEG::SEFormatJpeg::encodeWidget().
SEFormatJPEG::connect (m_encodeWidget , SIGNAL(optionHasChanged()) , this , SLOT(optionHasChanged()))
m_decodeWidget SEFormatJPEG::setObjectName ("DecodeWidget")
m_encodeWidget SEFormatJPEG::setObjectName ("EncodeWidget")
Referenced by SEFormatJPEG::GroupedImage::GroupedImage(), SEFormatJPEG::PixelGroup::PixelGroup(), and SEFormatJPEG::StegoTable::StegoTable().
Variable Documentation
F SEFormatJPEG::__pad0__
Definition at line 30 of file imagejpeg.cpp.
SEFormatJPEG::m_decodeWidget = NULL
Definition at line 28 of file seformatjpeg.cpp.
SEFormatJPEG::m_encodeWidget = NULL
Definition at line 27 of file seformatjpeg.cpp.
SEFormatJPEG::m_logger = new Logger(this)
Definition at line 25 of file seformatjpeg.cpp.