SilentEye: SilentEye::PreferenceDialog Class Reference
SilentEye::PreferenceDialog Class Reference
#include <preferencedialog.h>
Public Member Functions
PreferenceDialog (QWidget *parent=0)
Private Slots
void accepted ()
void rejected ()
void selectFile ()
Private Member Functions
void setConfig ()
Private Attributes
QMap< QString, int > m_imageFormatMap
QMap< QString, int > m_cryptoMap
Detailed Description
Definition at line 24 of file preferencedialog.h.
Constructor & Destructor Documentation
SilentEye::PreferenceDialog::PreferenceDialog (QWidget * parent = 0)
Definition at line 22 of file preferencedialog.cpp.
References accepted(), SilentEye::ModuleManager::count(), SilentEye::ModuleManager::CRYPTO, SilentEye::ModuleManager::getCategory(), SilentEye::ModuleManager::getList(), SilentEye::ModuleManager::IMAGEFORMAT, m_cryptoMap, m_imageFormatMap, SilentEyeFramework::ModuleInterface::name(), rejected(), selectFile(), setConfig(), SilentEyeFramework::ModuleInterface::status(), SilentEyeFramework::ModuleInterface::typeSupported(), and SilentEyeFramework::ModuleInterface::version().
Member Function Documentation
void SilentEye::PreferenceDialog::accepted () [private, slot]
Definition at line 99 of file preferencedialog.cpp.
References SilentEye::Controller::config, SilentEyeFramework::Config::save(), and SilentEyeFramework::Config::set().
Referenced by PreferenceDialog().
void SilentEye::PreferenceDialog::rejected () [private, slot]
Definition at line 108 of file preferencedialog.cpp.
References setConfig().
Referenced by PreferenceDialog().
void SilentEye::PreferenceDialog::selectFile () [private, slot]
Definition at line 113 of file preferencedialog.cpp.
Referenced by PreferenceDialog().
void SilentEye::PreferenceDialog::setConfig () [private]
Definition at line 69 of file preferencedialog.cpp.
References SilentEye::Controller::config, SilentEyeFramework::Config::get(), m_cryptoMap, and m_imageFormatMap.
Referenced by PreferenceDialog(), and rejected().
Member Data Documentation
QMap<QString, int> SilentEye::PreferenceDialog::m_cryptoMap [private]
Definition at line 30 of file preferencedialog.h.
Referenced by PreferenceDialog(), and setConfig().
QMap<QString, int> SilentEye::PreferenceDialog::m_imageFormatMap [private]
Definition at line 26 of file preferencedialog.h.
Referenced by PreferenceDialog(), and setConfig().
The documentation for this class was generated from the following files:
preferencedialog.h
preferencedialog.cpp