SilentEye: SilentEyeFramework::FormatModuleInterface Class Reference
SilentEyeFramework::FormatModuleInterface Class Reference
Common interface for media format plug-ins.
#include <formatmoduleinterface.h>
Signals
void optionChanged ()
Public Member Functions
virtual QWidget * encodeWidget ()=0
virtual bool isEncodeWidgetReady () const =0
virtual QWidget * decodeWidget ()=0
virtual bool isDecodeWidgetReady () const =0
Detailed Description
Common interface for media format plug-ins.
Definition at line 25 of file formatmoduleinterface.h.
Member Function Documentation
virtual QWidget* SilentEyeFramework::FormatModuleInterface::decodeWidget () [pure virtual]
Implemented in SEFormatBMP::SEFormatBmp, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::DecodeDialog::currentFormatWidget().
virtual QWidget* SilentEyeFramework::FormatModuleInterface::encodeWidget () [pure virtual]
Implemented in SEFormatBMP::SEFormatBmp, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::EncodeDialog::currentFormatWidget().
virtual bool SilentEyeFramework::FormatModuleInterface::isDecodeWidgetReady () const [pure virtual]
Implemented in SEFormatBMP::SEFormatBmp, SEFormatJPEG::SEFormatJpeg, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::DecodeDialog::ok().
virtual bool SilentEyeFramework::FormatModuleInterface::isEncodeWidgetReady () const [pure virtual]
Implemented in SEFormatBMP::SEFormatBmp, SEFormatJPEG::SEFormatJpeg, and SEFormatJPEG::SEFormatJpeg.
void SilentEyeFramework::FormatModuleInterface::optionChanged () [signal]
Reimplemented in SEFormatBMP::SEFormatBmp, SEFormatJPEG::SEFormatJpeg, and SEFormatJPEG::SEFormatJpeg.
The documentation for this class was generated from the following file:
sef/formatmoduleinterface.h