SilentEye: SEFormatJPEG::StegoTable Class Reference
SEFormatJPEG::StegoTable Class Reference
Manage the K stegano tables and the index table.
#include <stegotable.h>
Public Member Functions
StegoTable (const QString &, const quint8=DEFAULT_K, QObject *parent=0)
Generate the Stego Table according to the interval length and the passphrase.
~StegoTable ()
quint8 k ()
Intensity interval length value.
float computeNewMiv (float, bool)
bool computeValue (float, bool=true)
Compute hidden value according to stegotable.
QString toString ()
Compute a String representing all the stegano tables and the index table.
StegoTable (const QString &, const quint8=DEFAULT_K, QObject *parent=0)
Generate the Stego Table according to the interval length and the passphrase.
~StegoTable ()
quint8 k ()
Intensity interval length value.
float computeNewMiv (float, bool)
bool computeValue (float, bool=true)
QString toString ()
Compute a String representing all the stegano tables and the index table.
Private Member Functions
QBitArray getNextTable ()
BitArray table reprensenting current Stego table.
float computeMiddle (float)
Compute middle of an interval, depending on an intensity value.
void init_tables ()
Generate the Stego according to the md5 generated and the intensity interval.
void initIndexTable ()
Initialize the index table which determine which stego-table is going to be use.
QBitArray getNextTable ()
BitArray table reprensenting current Stego table.
float computeMiddle (float)
Compute middle of an interval, depending on an intensity value.
void init_tables ()
Generate the Stego according to the md5 generated and the intensity interval.
void initIndexTable ()
Initialize the index table which determine which stego-table is going to be use.
Private Attributes
QPointer< Logger > m_logger
Logger.
quint8 _k
Intensity interval and number of stego-tables.
quint8 _currentTable
Current stegano table used.
QVector< QBitArray > _stTables
stego tables
QVector< quint8 > _indexTable
extra index table
QString _md5
MD5 generated from the passphrase (required for table generation)
Detailed Description
Manage the K stegano tables and the index table.
Definition at line 33 of file stegotable.h.
Constructor & Destructor Documentation
SEFormatJPEG::StegoTable::StegoTable (const QString & passphrase, const quint8 k = DEFAULT_K, QObject * parent = 0)
Generate the Stego Table according to the interval length and the passphrase.
Definition at line 27 of file stegotable.cpp.
References _currentTable, _md5, init_tables(), m_logger, and SEFormatJPEG::setObjectName().
SEFormatJPEG::StegoTable::~StegoTable ()
Definition at line 45 of file stegotable.cpp.
SEFormatJPEG::StegoTable::StegoTable (const QString & , const quint8 = DEFAULT_K, QObject * parent = 0)
Generate the Stego Table according to the interval length and the passphrase.
SEFormatJPEG::StegoTable::~StegoTable ()
Member Function Documentation
float SEFormatJPEG::StegoTable::computeMiddle (float miv) [private]
Compute middle of an interval, depending on an intensity value.
Calculate the begining of an interval, depending on an intensity value.
Definition at line 51 of file stegotable.cpp.
References _k.
Referenced by computeNewMiv().
float SEFormatJPEG::StegoTable::computeMiddle (float) [private]
Compute middle of an interval, depending on an intensity value.
float SEFormatJPEG::StegoTable::computeNewMiv (float , bool)
float SEFormatJPEG::StegoTable::computeNewMiv (float oldMiv, bool value)
Definition at line 66 of file stegotable.cpp.
References _k, computeMiddle(), computeValue(), and getNextTable().
bool SEFormatJPEG::StegoTable::computeValue (float , bool = true)
bool SEFormatJPEG::StegoTable::computeValue (float miv, bool next = true)
Compute hidden value according to stegotable.
Definition at line 126 of file stegotable.cpp.
References _currentTable, _indexTable, _k, _stTables, and getNextTable().
Referenced by computeNewMiv().
QBitArray SEFormatJPEG::StegoTable::getNextTable () [private]
BitArray table reprensenting current Stego table.
BitArray table reprensenting the Stego tables.
Definition at line 136 of file stegotable.cpp.
References _currentTable, _indexTable, and _stTables.
Referenced by computeNewMiv(), and computeValue().
QBitArray SEFormatJPEG::StegoTable::getNextTable () [private]
BitArray table reprensenting current Stego table.
void SEFormatJPEG::StegoTable::init_tables () [private]
Generate the Stego according to the md5 generated and the intensity interval.
void SEFormatJPEG::StegoTable::init_tables () [private]
Generate the Stego according to the md5 generated and the intensity interval.
Definition at line 147 of file stegotable.cpp.
References _k, _md5, _stTables, and initIndexTable().
Referenced by StegoTable().
void SEFormatJPEG::StegoTable::initIndexTable () [private]
Initialize the index table which determine which stego-table is going to be use.
Definition at line 207 of file stegotable.cpp.
References _indexTable, _k, and _stTables.
Referenced by init_tables().
void SEFormatJPEG::StegoTable::initIndexTable () [private]
Initialize the index table which determine which stego-table is going to be use.
quint8 SEFormatJPEG::StegoTable::k ()
Intensity interval length value.
Definition at line 61 of file stegotable.cpp.
References _k.
quint8 SEFormatJPEG::StegoTable::k ()
Intensity interval length value.
QString SEFormatJPEG::StegoTable::toString ()
Compute a String representing all the stegano tables and the index table.
Definition at line 235 of file stegotable.cpp.
References _indexTable, and _stTables.
QString SEFormatJPEG::StegoTable::toString ()
Compute a String representing all the stegano tables and the index table.
Member Data Documentation
quint8 SEFormatJPEG::StegoTable::_currentTable [private]
Current stegano table used.
Definition at line 43 of file stegotable.h.
Referenced by computeValue(), getNextTable(), and StegoTable().
QVector< quint8 > SEFormatJPEG::StegoTable::_indexTable [private]
extra index table
Definition at line 49 of file stegotable.h.
Referenced by computeValue(), getNextTable(), initIndexTable(), and toString().
quint8 SEFormatJPEG::StegoTable::_k [private]
Intensity interval and number of stego-tables.
Definition at line 40 of file stegotable.h.
Referenced by computeMiddle(), computeNewMiv(), computeValue(), init_tables(), initIndexTable(), and k().
QString SEFormatJPEG::StegoTable::_md5 [private]
MD5 generated from the passphrase (required for table generation)
Definition at line 52 of file stegotable.h.
Referenced by init_tables(), and StegoTable().
QVector< QBitArray > SEFormatJPEG::StegoTable::_stTables [private]
stego tables
Definition at line 46 of file stegotable.h.
Referenced by computeValue(), getNextTable(), init_tables(), initIndexTable(), and toString().
QPointer< Logger > SEFormatJPEG::StegoTable::m_logger [private]
Logger.
Definition at line 37 of file stegotable.h.
Referenced by StegoTable().
The documentation for this class was generated from the following files:
modules/seformatjpeg/stegotable.h
modules/seformatjpegold/seformatjpeg/stegotable.h
modules/seformatjpeg/stegotable.cpp
modules/seformatjpegold/seformatjpeg/stegotable.cpp