SilentEye: SEFormatJPEG::GroupedImage Class Reference
SEFormatJPEG::GroupedImage Class Reference
This class reprensents the image where pixels are grouped in square blocs.
#include <groupedimage.h>
Public Member Functions
GroupedImage (QImage &, quint8, QObject *parent=0)
~GroupedImage ()
quint16 width ()
quint16 height ()
quint16 initialWidth ()
quint16 initialHeight ()
QPointer< PixelGroup > pixelGroup (quint16, quint16)
Get pixel group at specified position.
QImage * toImage ()
Convert into Image.
GroupedImage (QImage &, quint8, QObject *parent=0)
~GroupedImage ()
quint16 width ()
quint16 height ()
quint16 initialWidth ()
quint16 initialHeight ()
QPointer< PixelGroup > pixelGroup (quint16, quint16)
QImage * toImage ()
Static Public Member Functions
static void compactImage (QImage &, quint8)
Compact image (change luminance)
Private Member Functions
void compacteAndGroupImage (QImage &, quint8)
void compacteAndGroupImage (QImage &image, quint8)
Static Private Member Functions
static void compactPixel (QPointer< YCbCr >, quint8)
compact luminance (between +K et 255-K)
Private Attributes
QPointer< Logger > m_logger
Logger.
quint16 m_width
Number of pixel groups in the width of the image.
quint16 m_height
Number of pixel groups in the height of the image.
quint16 m_initialWidth
The initial width of the image, in pixel.
quint16 m_initialHeight
The initial height of the image, in pixel.
QImage::Format m_initialFormat
The initial format of the image (QImage::Format)
QVector< QPointer< PixelGroup > > m_pg
The image is stored in this two dimention array of PixelGroup.
Detailed Description
This class reprensents the image where pixels are grouped in square blocs.
Definition at line 81 of file groupedimage.h.
Constructor & Destructor Documentation
SEFormatJPEG::GroupedImage::GroupedImage (QImage & image, quint8 k, QObject * parent = 0)
Definition at line 193 of file groupedimage.cpp.
References compacteAndGroupImage(), height(), SEFormatJPEG::PixelGroup::height(), m_height, m_initialFormat, m_initialHeight, m_initialWidth, m_logger, m_pg, m_width, SEFormatJPEG::setObjectName(), width(), and SEFormatJPEG::PixelGroup::width().
SEFormatJPEG::GroupedImage::~GroupedImage ()
Definition at line 218 of file groupedimage.cpp.
SEFormatJPEG::GroupedImage::GroupedImage (QImage & , quint8 , QObject * parent = 0)
SEFormatJPEG::GroupedImage::~GroupedImage ()
Member Function Documentation
void SEFormatJPEG::GroupedImage::compacteAndGroupImage (QImage & image, quint8 k) [private]
Definition at line 269 of file groupedimage.cpp.
References height(), m_initialHeight, m_initialWidth, m_logger, m_pg, m_width, SEFormatJPEG::PixelGroup::width(), and width().
Referenced by GroupedImage().
void SEFormatJPEG::GroupedImage::compacteAndGroupImage (QImage & image, quint8) [private]
void SEFormatJPEG::GroupedImage::compactImage (QImage & image, quint8 k) [static]
Compact image (change luminance)
Definition at line 254 of file groupedimage.cpp.
References compactPixel().
void SEFormatJPEG::GroupedImage::compactPixel (QPointer< YCbCr > ycbcr, quint8 k) [static, private]
compact luminance (between +K et 255-K)
Definition at line 310 of file groupedimage.cpp.
Referenced by compactImage().
quint16 SEFormatJPEG::GroupedImage::height ()
quint16 SEFormatJPEG::GroupedImage::height ()
Definition at line 234 of file groupedimage.cpp.
References m_height.
Referenced by compacteAndGroupImage(), GroupedImage(), and toImage().
quint16 SEFormatJPEG::GroupedImage::initialHeight ()
Definition at line 244 of file groupedimage.cpp.
References m_initialHeight.
quint16 SEFormatJPEG::GroupedImage::initialHeight ()
quint16 SEFormatJPEG::GroupedImage::initialWidth ()
quint16 SEFormatJPEG::GroupedImage::initialWidth ()
Definition at line 239 of file groupedimage.cpp.
References m_initialWidth.
QPointer< PixelGroup > SEFormatJPEG::GroupedImage::pixelGroup (quint16 x, quint16 y)
Get pixel group at specified position.
Parameters:
x horizontal position
y vertical position
Definition at line 249 of file groupedimage.cpp.
References m_pg, and m_width.
QPointer<PixelGroup> SEFormatJPEG::GroupedImage::pixelGroup (quint16 , quint16)
QImage* SEFormatJPEG::GroupedImage::toImage ()
QImage * SEFormatJPEG::GroupedImage::toImage ()
Convert into Image.
Definition at line 315 of file groupedimage.cpp.
References height(), m_initialFormat, m_initialHeight, m_initialWidth, m_logger, m_pg, m_width, and SEFormatJPEG::PixelGroup::width().
quint16 SEFormatJPEG::GroupedImage::width ()
Definition at line 229 of file groupedimage.cpp.
References m_width.
Referenced by compacteAndGroupImage(), and GroupedImage().
quint16 SEFormatJPEG::GroupedImage::width ()
Member Data Documentation
quint16 SEFormatJPEG::GroupedImage::m_height [private]
Number of pixel groups in the height of the image.
Definition at line 89 of file groupedimage.h.
Referenced by GroupedImage(), and height().
QImage::Format SEFormatJPEG::GroupedImage::m_initialFormat [private]
The initial format of the image (QImage::Format)
Definition at line 95 of file groupedimage.h.
Referenced by GroupedImage(), and toImage().
quint16 SEFormatJPEG::GroupedImage::m_initialHeight [private]
The initial height of the image, in pixel.
Definition at line 93 of file groupedimage.h.
Referenced by compacteAndGroupImage(), GroupedImage(), initialHeight(), and toImage().
quint16 SEFormatJPEG::GroupedImage::m_initialWidth [private]
The initial width of the image, in pixel.
Definition at line 91 of file groupedimage.h.
Referenced by compacteAndGroupImage(), GroupedImage(), initialWidth(), and toImage().
QPointer< Logger > SEFormatJPEG::GroupedImage::m_logger [private]
Logger.
Definition at line 84 of file groupedimage.h.
Referenced by compacteAndGroupImage(), GroupedImage(), and toImage().
QVector< QPointer< PixelGroup > > SEFormatJPEG::GroupedImage::m_pg [private]
The image is stored in this two dimention array of PixelGroup.
Definition at line 98 of file groupedimage.h.
Referenced by compacteAndGroupImage(), GroupedImage(), pixelGroup(), and toImage().
quint16 SEFormatJPEG::GroupedImage::m_width [private]
Number of pixel groups in the width of the image.
Definition at line 87 of file groupedimage.h.
Referenced by compacteAndGroupImage(), GroupedImage(), pixelGroup(), toImage(), and width().
The documentation for this class was generated from the following files:
modules/seformatjpeg/groupedimage.h
modules/seformatjpegold/seformatjpeg/groupedimage.h
modules/seformatjpeg/groupedimage.cpp
modules/seformatjpegold/seformatjpeg/groupedimage.cpp