SilentEye: SilentEyeFramework::ModuleInterface Class Reference
SilentEyeFramework::ModuleInterface Class Reference
Common interface for all SilentEye's plug-in.
#include <moduleinterface.h>
Public Member Functions
virtual QString name () const =0
Plug-in name (ex: FooBar)
virtual QString version () const =0
Plug-in version (ex: 1.2.0)
virtual QString typeSupported () const =0
Type supported (ex: BMP, JPEG, AES128, etc.)
virtual QString status ()=0
Current status of the module (ex: KO|qca2-plugin-ossl missing)
Detailed Description
Common interface for all SilentEye's plug-in.
Definition at line 26 of file moduleinterface.h.
Member Function Documentation
virtual QString SilentEyeFramework::ModuleInterface::name () const [pure virtual]
Plug-in name (ex: FooBar)
Implemented in SECryptoAES::SECryptoAES, SECryptoAES256::SECryptoAES256, SEFormatBMP::SEFormatBmp, SEFormatJPEG::SEFormatJpeg, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::ModuleManager::loadPlugin(), SilentEye::EncodeDialog::ok(), SilentEye::DecodeDialog::ok(), and SilentEye::PreferenceDialog::PreferenceDialog().
virtual QString SilentEyeFramework::ModuleInterface::status () [pure virtual]
Current status of the module (ex: KO|qca2-plugin-ossl missing)
Implemented in SECryptoAES::SECryptoAES, SECryptoAES256::SECryptoAES256, SEFormatBMP::SEFormatBmp, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::PreferenceDialog::PreferenceDialog().
virtual QString SilentEyeFramework::ModuleInterface::typeSupported () const [pure virtual]
Type supported (ex: BMP, JPEG, AES128, etc.)
Implemented in SECryptoAES::SECryptoAES, SECryptoAES256::SECryptoAES256, SEFormatBMP::SEFormatBmp, SEFormatJPEG::SEFormatJpeg, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::OptionDialog::loadEncryptionTypes(), SilentEye::OptionDialog::loadFormats(), SilentEye::ModuleManager::loadPlugin(), SilentEye::PreferenceDialog::PreferenceDialog(), and SilentEye::PropertyDialog::setMedia().
virtual QString SilentEyeFramework::ModuleInterface::version () const [pure virtual]
Plug-in version (ex: 1.2.0)
Implemented in SECryptoAES::SECryptoAES, SECryptoAES256::SECryptoAES256, SEFormatBMP::SEFormatBmp, SEFormatJPEG::SEFormatJpeg, and SEFormatJPEG::SEFormatJpeg.
Referenced by SilentEye::PreferenceDialog::PreferenceDialog().
The documentation for this class was generated from the following file:
sef/moduleinterface.h