SilentEye: SilentEye::EncodeDialog Class Reference
SilentEye::EncodeDialog Class Reference
Dialog for generic encoding process.
#include <encodedialog.h>
Signals
void encodedImage (QString)
Public Member Functions
EncodeDialog (QWidget *parent=0)
Protected Member Functions
QWidget * currentFormatWidget (FormatModuleInterface *)
Private Slots
void ok ()
void showEvent (QShowEvent *)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
Detailed Description
Dialog for generic encoding process.
Definition at line 24 of file encodedialog.h.
Constructor & Destructor Documentation
SilentEye::EncodeDialog::EncodeDialog (QWidget * parent = 0)
Member Function Documentation
QWidget * SilentEye::EncodeDialog::currentFormatWidget (FormatModuleInterface * module) [protected, virtual]
Implements SilentEye::OptionDialog.
Definition at line 88 of file encodedialog.cpp.
References SilentEyeFramework::FormatModuleInterface::encodeWidget().
void SilentEye::EncodeDialog::dragEnterEvent (QDragEnterEvent * event) [private, slot]
Definition at line 61 of file encodedialog.cpp.
References SilentEye::OptionDialog::m_logger.
void SilentEye::EncodeDialog::dropEvent (QDropEvent * event) [private, slot]
Definition at line 69 of file encodedialog.cpp.
References SilentEye::OptionDialog::addFile().
void SilentEye::EncodeDialog::encodedImage (QString) [signal]
Referenced by ok().
void SilentEye::EncodeDialog::ok () [private, virtual, slot]
Implements SilentEye::OptionDialog.
Definition at line 96 of file encodedialog.cpp.
References SilentEye::OptionDialog::currentCharset(), SilentEye::OptionDialog::currentCryptoModule(), SilentEye::OptionDialog::currentFormatModule(), SilentEye::OptionDialog::displayException(), SilentEyeFramework::CryptoModuleInterface::encode(), encodedImage(), SilentEye::Controller::instance(), SilentEye::OptionDialog::isDialogReady(), SilentEye::OptionDialog::m_filePath, SilentEye::OptionDialog::m_logger, SilentEye::OptionDialog::m_md, and SilentEyeFramework::ModuleInterface::name().
void SilentEye::EncodeDialog::showEvent (QShowEvent * event) [private, slot]
Definition at line 43 of file encodedialog.cpp.
References SilentEye::OptionDialog::checkCryptoPassword(), SilentEye::OptionDialog::formatChanged(), SilentEye::Controller::instance(), SilentEye::OptionDialog::m_logger, SilentEye::OptionDialog::m_md, SilentEye::OptionDialog::removeFile(), SilentEye::setWindowTitle(), and SilentEye::OptionDialog::updateDialogSize().
The documentation for this class was generated from the following files:
encodedialog.h
encodedialog.cpp