SilentEye: SilentEye::ModuleManager Class Reference
SilentEye::ModuleManager Class Reference
Load and manage SilentEye's Plug-ins.
#include <modulemanager.h>
Public Types
enum Category {
IMAGEFORMAT, AUDIOFORMAT, VIDEOFORMAT, CRYPTO,
C_UNDEF
}
Static Public Member Functions
static QList< ModuleInterface * > & getList ()
static QMap< QString,
ModuleInterface * > & get (Category cat)
static ModuleInterface * get (Category cat, QString type)
static Category getCategory (ModuleInterface *)
static int count ()
static int count (Category cat)
static void load ()
Static Private Member Functions
static void loadPlugin (QObject *, QString="Unknown")
Static Private Attributes
static Logger m_logger
static QMap< Category, QMap
< QString, ModuleInterface * > > m_modulesMap
static QMap< QString,
ModuleInterface * > m_emptyMap
static QList< ModuleInterface * > m_modulesList
Detailed Description
Load and manage SilentEye's Plug-ins.
Definition at line 38 of file modulemanager.h.
Member Enumeration Documentation
enum SilentEye::ModuleManager::Category
Enumerator:
IMAGEFORMAT
AUDIOFORMAT
VIDEOFORMAT
CRYPTO
C_UNDEF
Definition at line 41 of file modulemanager.h.
Member Function Documentation
int SilentEye::ModuleManager::count () [static]
Definition at line 71 of file modulemanager.cpp.
References m_modulesList.
Referenced by count(), SilentEye::PreferenceDialog::PreferenceDialog(), and SilentEye::OptionDialog::setupDialog().
int SilentEye::ModuleManager::count (Category cat) [static]
Definition at line 77 of file modulemanager.cpp.
References count(), and m_modulesMap.
QMap< QString, ModuleInterface * > & SilentEye::ModuleManager::get (Category cat) [static]
Definition at line 35 of file modulemanager.cpp.
References m_emptyMap, and m_modulesMap.
Referenced by SilentEye::OptionDialog::currentCryptoModule(), SilentEye::OptionDialog::currentFormatModule(), SilentEye::OptionDialog::formatChanged(), SilentEye::OptionDialog::loadEncryptionTypes(), SilentEye::OptionDialog::loadFormats(), and SilentEye::PropertyDialog::setMedia().
ModuleInterface * SilentEye::ModuleManager::get (Category cat, QString type) [static]
Definition at line 44 of file modulemanager.cpp.
References m_modulesMap.
ModuleManager::Category SilentEye::ModuleManager::getCategory (ModuleInterface * module) [static]
Definition at line 52 of file modulemanager.cpp.
References C_UNDEF, and m_modulesMap.
Referenced by SilentEye::PreferenceDialog::PreferenceDialog().
QList< ModuleInterface * > & SilentEye::ModuleManager::getList () [static]
Definition at line 29 of file modulemanager.cpp.
References m_modulesList.
Referenced by SilentEye::PreferenceDialog::PreferenceDialog().
void SilentEye::ModuleManager::load () [static]
Definition at line 84 of file modulemanager.cpp.
References SilentEyeFramework::Logger::debug(), loadPlugin(), m_logger, and SilentEyeFramework::Logger::warning().
void SilentEye::ModuleManager::loadPlugin (QObject * plugin, QString error = "Unknown") [static, private]
Definition at line 112 of file modulemanager.cpp.
References AUDIOFORMAT, CRYPTO, SilentEyeFramework::Logger::debug(), IMAGEFORMAT, SilentEyeFramework::Logger::info(), m_logger, m_modulesList, m_modulesMap, SilentEyeFramework::ModuleInterface::name(), SilentEyeFramework::ModuleInterface::typeSupported(), VIDEOFORMAT, and SilentEyeFramework::Logger::warning().
Referenced by load().
Member Data Documentation
QMap< QString, ModuleInterface * > SilentEye::ModuleManager::m_emptyMap [static, private]
Definition at line 46 of file modulemanager.h.
Referenced by get().
Logger SilentEye::ModuleManager::m_logger [static, private]
Definition at line 44 of file modulemanager.h.
Referenced by load(), and loadPlugin().
QList< ModuleInterface * > SilentEye::ModuleManager::m_modulesList [static, private]
Definition at line 47 of file modulemanager.h.
Referenced by count(), getList(), and loadPlugin().
QMap< ModuleManager::Category, QMap< QString, ModuleInterface * > > SilentEye::ModuleManager::m_modulesMap [static, private]
Definition at line 45 of file modulemanager.h.
Referenced by count(), get(), getCategory(), and loadPlugin().
The documentation for this class was generated from the following files:
modulemanager.h
modulemanager.cpp