SilentEye: SEFormatJPEG::SEFormatJpeg Class Reference
SEFormatJPEG::SEFormatJpeg Class Reference
Official module for support of JPEG image (using LSB)
#include <seformatjpeg.h>
Signals
void optionChanged ()
void optionChanged ()
Public Member Functions
SEFormatJpeg ()
~SEFormatJpeg ()
QWidget * encodeWidget ()
QWidget * decodeWidget ()
bool isEncodeWidgetReady () const
bool isDecodeWidgetReady () const
QPointer< Image > encodeImage (QPointer< Image >, bool=false)
QPointer< Image > decodeImage (QPointer< Image >, bool=false)
QString typeSupported () const
Type supported (ex: BMP, JPEG, AES128, etc.)
QString name () const
Plug-in name (ex: FooBar)
QString version () const
Plug-in version (ex: 1.2.0)
QString status ()
Current status of the module (ex: KO|qca2-plugin-ossl missing)
SEFormatJpeg ()
~SEFormatJpeg ()
QWidget * encodeWidget () const
QWidget * decodeWidget () const
bool isEncodeWidgetReady () const
bool isDecodeWidgetReady () const
QPointer< Image > encodeImage (QPointer< Image >, bool=false)
QPointer< Image > decodeImage (QPointer< Image >, bool=false)
QString typeSupported () const
Type supported (ex: BMP, JPEG, AES128, etc.)
QString name () const
Plug-in name (ex: FooBar)
QString version () const
Plug-in version (ex: 1.2.0)
QString status () const
Private Slots
void optionHasChanged ()
void optionHasChanged ()
Private Member Functions
Q_INTERFACES (SilentEyeFramework::ImageModuleInterface)
QPointer< Image > updateImage (QPointer< Image >, OptionWidget *, bool)
Q_INTERFACES (SilentEyeFramework::ImageModuleInterface)
QPointer< Image > updateImage (QPointer< Image >, OptionWidget *, bool)
Private Attributes
QPointer< Logger > m_logger
OptionWidget * m_encodeWidget
OptionWidget * m_decodeWidget
Detailed Description
Official module for support of JPEG image (using LSB)
Official module for support of BMP image (using LSB)
Definition at line 33 of file seformatjpeg.h.
Constructor & Destructor Documentation
SEFormatJPEG::SEFormatJpeg::SEFormatJpeg ()
SEFormatJPEG::SEFormatJpeg::~SEFormatJpeg ()
Definition at line 31 of file seformatjpeg.cpp.
References m_decodeWidget, m_encodeWidget, and m_logger.
SEFormatJPEG::SEFormatJpeg::SEFormatJpeg ()
SEFormatJPEG::SEFormatJpeg::~SEFormatJpeg ()
Member Function Documentation
QPointer< Image > SEFormatJPEG::SEFormatJpeg::decodeImage (QPointer< Image > img, bool dontDuplicate = false) [virtual]
Implements SilentEyeFramework::ImageModuleInterface.
Definition at line 82 of file seformatjpeg.cpp.
References decodeWidget(), and updateImage().
QPointer<Image> SEFormatJPEG::SEFormatJpeg::decodeImage (QPointer< Image > , bool = false) [virtual]
Implements SilentEyeFramework::ImageModuleInterface.
QWidget * SEFormatJPEG::SEFormatJpeg::decodeWidget () const
Definition at line 62 of file seformatjpeg.cpp.
References m_decodeWidget.
QWidget * SEFormatJPEG::SEFormatJpeg::decodeWidget () [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 66 of file seformatjpeg.cpp.
References SEFormatJPEG::OptionWidget::hideQuality(), and m_decodeWidget.
Referenced by decodeImage().
QPointer<Image> SEFormatJPEG::SEFormatJpeg::encodeImage (QPointer< Image > , bool = false) [virtual]
Implements SilentEyeFramework::ImageModuleInterface.
QPointer< Image > SEFormatJPEG::SEFormatJpeg::encodeImage (QPointer< Image > img, bool dontDuplicate = false) [virtual]
Implements SilentEyeFramework::ImageModuleInterface.
Definition at line 77 of file seformatjpeg.cpp.
References encodeWidget(), and updateImage().
QWidget * SEFormatJPEG::SEFormatJpeg::encodeWidget () const
Definition at line 57 of file seformatjpeg.cpp.
References m_encodeWidget.
QWidget * SEFormatJPEG::SEFormatJpeg::encodeWidget () [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 55 of file seformatjpeg.cpp.
References SEFormatJPEG::connect(), m_encodeWidget, and optionHasChanged().
Referenced by encodeImage().
bool SEFormatJPEG::SEFormatJpeg::isDecodeWidgetReady () const [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 118 of file seformatjpeg.cpp.
bool SEFormatJPEG::SEFormatJpeg::isDecodeWidgetReady () const [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
bool SEFormatJPEG::SEFormatJpeg::isEncodeWidgetReady () const [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
bool SEFormatJPEG::SEFormatJpeg::isEncodeWidgetReady () const [virtual]
Implements SilentEyeFramework::FormatModuleInterface.
Definition at line 113 of file seformatjpeg.cpp.
QString SEFormatJPEG::SEFormatJpeg::name () const [virtual]
Plug-in name (ex: FooBar)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 40 of file seformatjpeg.cpp.
QString SEFormatJPEG::SEFormatJpeg::name () const [virtual]
Plug-in name (ex: FooBar)
Implements SilentEyeFramework::ModuleInterface.
void SEFormatJPEG::SEFormatJpeg::optionChanged () [signal]
Reimplemented from SilentEyeFramework::FormatModuleInterface.
void SEFormatJPEG::SEFormatJpeg::optionChanged () [signal]
Reimplemented from SilentEyeFramework::FormatModuleInterface.
Referenced by optionHasChanged().
void SEFormatJPEG::SEFormatJpeg::optionHasChanged () [private, slot]
void SEFormatJPEG::SEFormatJpeg::optionHasChanged () [private, slot]
Definition at line 123 of file seformatjpeg.cpp.
References optionChanged().
Referenced by encodeWidget().
SEFormatJPEG::SEFormatJpeg::Q_INTERFACES (SilentEyeFramework::ImageModuleInterface) [private]
SEFormatJPEG::SEFormatJpeg::Q_INTERFACES (SilentEyeFramework::ImageModuleInterface) [private]
QString SEFormatJPEG::SEFormatJpeg::status () [virtual]
Current status of the module (ex: KO|qca2-plugin-ossl missing)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 50 of file seformatjpeg.cpp.
QString SEFormatJPEG::SEFormatJpeg::status () const
Definition at line 52 of file seformatjpeg.cpp.
QString SEFormatJPEG::SEFormatJpeg::typeSupported () const [virtual]
Type supported (ex: BMP, JPEG, AES128, etc.)
Implements SilentEyeFramework::ModuleInterface.
QString SEFormatJPEG::SEFormatJpeg::typeSupported () const [virtual]
Type supported (ex: BMP, JPEG, AES128, etc.)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 108 of file seformatjpeg.cpp.
QPointer< Image > SEFormatJPEG::SEFormatJpeg::updateImage (QPointer< Image > img, OptionWidget * w, bool dontDuplicate) [private]
Definition at line 87 of file seformatjpeg.cpp.
References SEFormatJPEG::OptionWidget::headerPosition(), SEFormatJPEG::OptionWidget::k(), SEFormatJPEG::OptionWidget::passphrase(), SEFormatJPEG::OptionWidget::quality(), SEFormatJPEG::ImageJPEG::setHeaderPosition(), SEFormatJPEG::ImageJPEG::setK(), SEFormatJPEG::ImageJPEG::setPassphrase(), and SEFormatJPEG::ImageJPEG::setQuality().
Referenced by decodeImage(), and encodeImage().
QPointer<Image> SEFormatJPEG::SEFormatJpeg::updateImage (QPointer< Image > , OptionWidget * , bool) [private]
QString SEFormatJPEG::SEFormatJpeg::version () const [virtual]
Plug-in version (ex: 1.2.0)
Implements SilentEyeFramework::ModuleInterface.
QString SEFormatJPEG::SEFormatJpeg::version () const [virtual]
Plug-in version (ex: 1.2.0)
Implements SilentEyeFramework::ModuleInterface.
Definition at line 45 of file seformatjpeg.cpp.
Member Data Documentation
OptionWidget * SEFormatJPEG::SEFormatJpeg::m_decodeWidget [private]
Definition at line 41 of file seformatjpeg.h.
Referenced by decodeWidget(), and ~SEFormatJpeg().
OptionWidget * SEFormatJPEG::SEFormatJpeg::m_encodeWidget [private]
Definition at line 40 of file seformatjpeg.h.
Referenced by encodeWidget(), and ~SEFormatJpeg().
QPointer< Logger > SEFormatJPEG::SEFormatJpeg::m_logger [private]
Definition at line 39 of file seformatjpeg.h.
Referenced by ~SEFormatJpeg().
The documentation for this class was generated from the following files:
modules/seformatjpeg/seformatjpeg.h
modules/seformatjpegold/seformatjpeg/seformatjpeg.h
modules/seformatjpeg/seformatjpeg.cpp
modules/seformatjpegold/seformatjpeg/seformatjpeg.cpp