SilentEye: SEFormatBMP Namespace Reference
SEFormatBMP Namespace Reference
SilentEye official module for support of BMP image.
Classes
class ImageBMP
class OptionWidget
class SEFormatBmp
Official module for support of BMP image (using LSB)
Functions
setColorUsed (true, false, false)
setObjectName ("ImageBMP")
setupUi (this)
advancedWidget setVisible (false)
settingsChanged ()
connect (advancedButton, SIGNAL(toggled(bool)), this, SLOT(advButtonPressed(bool)))
connect (qualityComboBox, SIGNAL(currentIndexChanged(int)), this, SLOT(qualityChanged(int)))
connect (redCheckBox, SIGNAL(stateChanged(int)), this, SLOT(settingsChanged(int)))
connect (greenCheckBox, SIGNAL(stateChanged(int)), this, SLOT(settingsChanged(int)))
connect (blueCheckBox, SIGNAL(stateChanged(int)), this, SLOT(settingsChanged(int)))
connect (nbBitsSpinBox, SIGNAL(valueChanged(int)), this, SLOT(settingsChanged(int)))
Variables
F __pad0__
m_headerPosition = TOP
m_distribution = INLINE
m_logger = new Logger(this)
m_dontUpdate = false
m_encodeWidget = NULL
m_decodeWidget = NULL
Detailed Description
SilentEye official module for support of BMP image.
Function Documentation
SEFormatBMP::connect (advancedButton , SIGNAL(toggled(bool)) , this , SLOT(advButtonPressed(bool)))
Referenced by SEFormatBMP::SEFormatBmp::encodeWidget().
SEFormatBMP::connect (nbBitsSpinBox , SIGNAL(valueChanged(int)) , this , SLOT(settingsChanged(int)))
SEFormatBMP::connect (redCheckBox , SIGNAL(stateChanged(int)) , this , SLOT(settingsChanged(int)))
SEFormatBMP::connect (greenCheckBox , SIGNAL(stateChanged(int)) , this , SLOT(settingsChanged(int)))
SEFormatBMP::connect (blueCheckBox , SIGNAL(stateChanged(int)) , this , SLOT(settingsChanged(int)))
SEFormatBMP::connect (qualityComboBox , SIGNAL(currentIndexChanged(int)) , this , SLOT(qualityChanged(int)))
SEFormatBMP::setColorUsed (true , false , false)
Referenced by SEFormatBMP::ImageBMP::ImageBMP().
SEFormatBMP::setObjectName ("ImageBMP")
Referenced by SilentEyeFramework::Audio::Audio(), SilentEyeFramework::Config::Config(), SilentEye::Controller::Controller(), SilentEyeFramework::Data::Data(), SilentEyeFramework::Image::Image(), SEFormatBMP::ImageBMP::ImageBMP(), SilentEyeFramework::Media::Media(), SilentEyeFramework::Media(), SilentEye::PropertyDialog::PropertyDialog(), SilentEye::UpdateDialog::UpdateDialog(), and SilentEyeFramework::Video::Video().
SEFormatBMP::settingsChanged ()
Referenced by SEFormatWAV::OptionWidget::qualityChanged().
SEFormatBMP::setupUi (this)
Referenced by SilentEye::AboutDialog::AboutDialog(), SilentEye::MainWindow::MainWindow(), SilentEye::MediaWidget::MediaWidget(), SilentEye::OptionDialog::OptionDialog(), SilentEye::PreferenceDialog::PreferenceDialog(), SilentEye::PropertyDialog::PropertyDialog(), and SilentEye::UpdateDialog::UpdateDialog().
advancedWidget SEFormatBMP::setVisible (false)
Variable Documentation
F SEFormatBMP::__pad0__
Definition at line 26 of file imagebmp.cpp.
SEFormatBMP::m_decodeWidget = NULL
Definition at line 27 of file seformatbmp.cpp.
SEFormatBMP::m_distribution = INLINE
Definition at line 29 of file imagebmp.cpp.
Referenced by SEFormatBMP::ImageBMP::ImageBMP().
SEFormatBMP::m_dontUpdate = false
Definition at line 27 of file optionwidget.cpp.
Referenced by SEFormatWAV::OptionWidget::qualityChanged(), and SEFormatWAV::OptionWidget::settingsChanged().
SEFormatBMP::m_encodeWidget = NULL
Definition at line 26 of file seformatbmp.cpp.
SEFormatBMP::m_headerPosition = TOP
Definition at line 28 of file imagebmp.cpp.
Referenced by SEFormatBMP::ImageBMP::ImageBMP().
SEFormatBMP::m_logger = new Logger(this)
Definition at line 31 of file imagebmp.cpp.
Referenced by SEFormatBMP::ImageBMP::ImageBMP().