SilentEye: SilentEyeFramework Namespace Reference
SilentEyeFramework Namespace Reference
Framework used by SilentEye and these plug-ins.
Classes
class Audio
Generic representation of audio which can load and hide specific data according to it's format.
class Config
Manage configuration for application (read/write in xml file)
class CryptoModuleInterface
Common interface for cryptography plug-ins.
class Data
Data encapsulation.
class EncodedData
EncodedData is a data manager used to read information bit per bit.
class FormatModuleInterface
Common interface for media format plug-ins.
class Image
Generic representation of image which can load and hide specific data according to it's format.
class ImageModuleInterface
Common interface for image format plug-ins.
class Logger
Provides methods for multi-level logging into logfile and console.
class Media
Generic representation of Media which can load and hide specific data according to it's format.
class ModuleException
Exception used by all SilentEye's plug-in.
class ModuleInterface
Common interface for all SilentEye's plug-in.
class SilentEyeException
Internal exception only used by SilentEyeFramework.
class Video
Generic representation of video which can load and hide specific data according to it's format.
class VideoModuleInterface
Common interface for video format plug-ins.
Functions
readWaveHeader ()
virtual QPointer< Audio > decodeAudio (QPointer< Audio >, bool=false)=0
F Media ()
Variables
F __pad0__
m_type = AUDIO
F bool = false) = 0
m_logger = new Logger(this)
m_isLoaded = false
m_filename = "se-noname.conf"
m_filepath = "/tmp/"
QString m_fileName = "application.log"
Detailed Description
Framework used by SilentEye and these plug-ins.
Function Documentation
virtual QPointer<Audio> SilentEyeFramework::decodeAudio (QPointer< Audio > , bool = false) [pure virtual]
Referenced by SilentEye::DecodeDialog::ok().
F SilentEyeFramework::Media ()
Definition at line 22 of file image.cpp.
References m_type, and SEFormatBMP::setObjectName().
Referenced by SilentEye::OptionDialog::setMedia().
SilentEyeFramework::readWaveHeader ()
Referenced by SilentEyeFramework::Audio::Audio().
Variable Documentation
F SilentEyeFramework::__pad0__
Definition at line 34 of file audio.cpp.
F SilentEyeFramework::bool = false) = 0
Definition at line 29 of file audiomoduleinterface.h.
QString SilentEyeFramework::m_fileName = "application.log"
Definition at line 25 of file logger.cpp.
Referenced by SilentEyeFramework::Logger::init(), and SilentEyeFramework::Logger::setFileName().
SilentEyeFramework::m_filename = "se-noname.conf"
Definition at line 27 of file config.cpp.
Referenced by SilentEyeFramework::Config::Config().
SilentEyeFramework::m_filepath = "/tmp/"
Definition at line 28 of file config.cpp.
Referenced by SilentEyeFramework::Config::Config().
SilentEyeFramework::m_isLoaded = false
Definition at line 26 of file config.cpp.
Referenced by SilentEyeFramework::Config::Config().
SilentEyeFramework::m_logger = new Logger(this)
Definition at line 25 of file config.cpp.
Referenced by SilentEyeFramework::Config::Config().
SilentEyeFramework::m_type = AUDIO
Definition at line 35 of file audio.cpp.
Referenced by SilentEyeFramework::Audio::Audio(), SilentEyeFramework::Image::Image(), Media(), and SilentEyeFramework::Video::Video().