SilentEye: SilentEye::PropertyDialog Class Reference
SilentEye::PropertyDialog Class Reference
Show current media properties.
#include <propertydialog.h>
Public Member Functions
PropertyDialog (QWidget *parent=0)
~PropertyDialog ()
void setMedia (Media *)
Private Slots
void formatChanged (const QString &)
Private Attributes
QPointer< Logger > m_logger
QMap< QString, long > m_capacityMap
Media * m_md
Detailed Description
Show current media properties.
Definition at line 29 of file propertydialog.h.
Constructor & Destructor Documentation
SilentEye::PropertyDialog::PropertyDialog (QWidget * parent = 0)
Definition at line 25 of file propertydialog.cpp.
References formatChanged(), m_logger, and m_md.
SilentEye::PropertyDialog::~PropertyDialog ()
Definition at line 36 of file propertydialog.cpp.
References m_logger.
Member Function Documentation
void SilentEye::PropertyDialog::formatChanged (const QString & text) [private, slot]
Definition at line 146 of file propertydialog.cpp.
References m_capacityMap.
Referenced by PropertyDialog(), and setMedia().
void SilentEye::PropertyDialog::setMedia (Media * md)
Definition at line 44 of file propertydialog.cpp.
References SilentEye::ModuleManager::AUDIOFORMAT, SilentEyeFramework::Audio::bitRate(), SilentEyeFramework::Media::capacity(), SilentEyeFramework::Audio::duration(), SilentEyeFramework::Media::filePath(), SilentEyeFramework::Audio::format(), formatChanged(), SilentEye::ModuleManager::get(), SilentEye::ModuleManager::IMAGEFORMAT, m_capacityMap, m_md, SilentEyeFramework::Image::quality(), SilentEyeFramework::Media::type(), SilentEyeFramework::ModuleInterface::typeSupported(), and SilentEye::ModuleManager::VIDEOFORMAT.
Referenced by SilentEye::MainWindow::execPropertyDialog().
Member Data Documentation
QMap<QString, long> SilentEye::PropertyDialog::m_capacityMap [private]
Definition at line 35 of file propertydialog.h.
Referenced by formatChanged(), and setMedia().
QPointer<Logger> SilentEye::PropertyDialog::m_logger [private]
Definition at line 31 of file propertydialog.h.
Referenced by PropertyDialog(), and ~PropertyDialog().
Media* SilentEye::PropertyDialog::m_md [private]
Definition at line 37 of file propertydialog.h.
Referenced by PropertyDialog(), and setMedia().
The documentation for this class was generated from the following files:
propertydialog.h
propertydialog.cpp